import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🚀 Seeding 100+ NEW problems (scaling to 150+ total)...\n");

  const problems = [
    // ═══════════════════════════════════════════════════════
    // ARRAYS — 10 new problems
    // ═══════════════════════════════════════════════════════
    {
      slug: "move-zeroes",
      title: "Move Zeroes",
      description: "Given an integer array `nums`, move all `0`'s to the end while maintaining the relative order of the non-zero elements. Do it in-place.\n\n**Example:**\n```\nInput: nums = [0,1,0,3,12]\nOutput: [1,3,12,0,0]\n```",
      difficulty: "easy",
      category: "arrays",
      starterCode: "def move_zeroes(nums):\n    pass\n\nimport json\nnums = json.loads(input())\nmove_zeroes(nums)\nprint(json.dumps(nums))",
      testCases: JSON.stringify([
        { input: "[0,1,0,3,12]", expected: "[1, 3, 12, 0, 0]" },
        { input: "[0]", expected: "[0]" },
        { input: "[1,2,3]", expected: "[1, 2, 3]" },
      ]),
      solutionApproach: "Two pointers: slow tracks insertion position. Fast scans. Swap non-zero to slow position. O(n) time, O(1) space.",
      companyTags: JSON.stringify(["Meta", "Amazon", "Apple"]),
    },
    {
      slug: "find-disappeared-numbers",
      title: "Find All Numbers Disappeared in Array",
      description: "Given an array `nums` of `n` integers where `nums[i]` is in `[1, n]`, return all integers in `[1, n]` that do not appear in `nums`.\n\n**Example:**\n```\nInput: nums = [4,3,2,7,8,2,3,1]\nOutput: [5,6]\n```\n\nDo it without extra space (O(1) besides result).",
      difficulty: "easy",
      category: "arrays",
      starterCode: "def find_disappeared(nums):\n    pass\n\nimport json\nnums = json.loads(input())\nprint(json.dumps(find_disappeared(nums)))",
      testCases: JSON.stringify([
        { input: "[4,3,2,7,8,2,3,1]", expected: "[5, 6]" },
        { input: "[1,1]", expected: "[2]" },
      ]),
      solutionApproach: "Mark visited by negating nums[abs(nums[i])-1]. Missing numbers are at positive indices. O(n) time, O(1) space.",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },
    {
      slug: "majority-element",
      title: "Majority Element",
      description: "Given an array `nums` of size `n`, return the majority element (appears more than ⌊n/2⌋ times). The majority element always exists.\n\n**Example:**\n```\nInput: nums = [2,2,1,1,1,2,2]\nOutput: 2\n```",
      difficulty: "easy",
      category: "arrays",
      starterCode: "def majority_element(nums):\n    pass\n\nimport json\nnums = json.loads(input())\nprint(majority_element(nums))",
      testCases: JSON.stringify([
        { input: "[3,2,3]", expected: "3" },
        { input: "[2,2,1,1,1,2,2]", expected: "2" },
      ]),
      solutionApproach: "Boyer-Moore Voting Algorithm: count for candidate. If count=0, pick new candidate. O(n) time, O(1) space.",
      companyTags: JSON.stringify(["Amazon", "Google", "Microsoft"]),
    },
    {
      slug: "single-number",
      title: "Single Number",
      description: "Given a non-empty array where every element appears twice except one, find that single one.\n\n**Example:**\n```\nInput: nums = [4,1,2,1,2]\nOutput: 4\n```\n\nDo it in O(n) time with O(1) space.",
      difficulty: "easy",
      category: "arrays",
      starterCode: "def single_number(nums):\n    pass\n\nimport json\nnums = json.loads(input())\nprint(single_number(nums))",
      testCases: JSON.stringify([
        { input: "[2,2,1]", expected: "1" },
        { input: "[4,1,2,1,2]", expected: "4" },
        { input: "[1]", expected: "1" },
      ]),
      solutionApproach: "XOR all numbers. a^a=0 and a^0=a. All pairs cancel, leaving the single number. O(n) time, O(1) space.",
      companyTags: JSON.stringify(["Amazon", "Apple", "Google"]),
    },
    {
      slug: "pascals-triangle",
      title: "Pascal's Triangle",
      description: "Given an integer `numRows`, return the first `numRows` of Pascal's triangle.\n\n**Example:**\n```\nInput: numRows = 5\nOutput: [[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]]\n```",
      difficulty: "easy",
      category: "arrays",
      starterCode: "def generate(num_rows):\n    pass\n\nimport json\nn = int(input())\nprint(json.dumps(generate(n)))",
      testCases: JSON.stringify([
        { input: "5", expected: "[[1], [1, 1], [1, 2, 1], [1, 3, 3, 1], [1, 4, 6, 4, 1]]" },
        { input: "1", expected: "[[1]]" },
      ]),
      solutionApproach: "Build row by row. Each element is sum of two elements above it. O(n²).",
      companyTags: JSON.stringify(["Amazon", "Microsoft", "Google"]),
    },
    {
      slug: "next-permutation",
      title: "Next Permutation",
      description: "Given an array of integers, rearrange it to the next lexicographically greater permutation. If not possible, rearrange to the lowest (sorted ascending).\n\n**Example:**\n```\nInput: nums = [1,2,3]\nOutput: [1,3,2]\n```\n```\nInput: nums = [3,2,1]\nOutput: [1,2,3]\n```",
      difficulty: "medium",
      category: "arrays",
      starterCode: "def next_permutation(nums):\n    pass\n\nimport json\nnums = json.loads(input())\nnext_permutation(nums)\nprint(json.dumps(nums))",
      testCases: JSON.stringify([
        { input: "[1,2,3]", expected: "[1, 3, 2]" },
        { input: "[3,2,1]", expected: "[1, 2, 3]" },
        { input: "[1,1,5]", expected: "[1, 5, 1]" },
      ]),
      solutionApproach: "Find rightmost ascending pair, swap with smallest larger element to the right, reverse suffix. O(n).",
      companyTags: JSON.stringify(["Google", "Amazon", "Meta"]),
    },
    {
      slug: "sort-colors",
      title: "Sort Colors (Dutch National Flag)",
      description: "Given an array `nums` with `n` objects colored red (0), white (1), or blue (2), sort them in-place.\n\n**Example:**\n```\nInput: nums = [2,0,2,1,1,0]\nOutput: [0,0,1,1,2,2]\n```\n\nDo not use the library's sort function.",
      difficulty: "medium",
      category: "arrays",
      starterCode: "def sort_colors(nums):\n    pass\n\nimport json\nnums = json.loads(input())\nsort_colors(nums)\nprint(json.dumps(nums))",
      testCases: JSON.stringify([
        { input: "[2,0,2,1,1,0]", expected: "[0, 0, 1, 1, 2, 2]" },
        { input: "[2,0,1]", expected: "[0, 1, 2]" },
      ]),
      solutionApproach: "Dutch National Flag: three pointers (low, mid, high). Swap 0s to front, 2s to back. O(n), single pass.",
      companyTags: JSON.stringify(["Amazon", "Microsoft", "Google"]),
    },
    {
      slug: "find-minimum-rotated-sorted",
      title: "Find Minimum in Rotated Sorted Array",
      description: "Given a sorted rotated array of unique elements, find the minimum element.\n\n**Example:**\n```\nInput: nums = [3,4,5,1,2]\nOutput: 1\n```\n\nMust be O(log n).",
      difficulty: "medium",
      category: "arrays",
      starterCode: "def find_min(nums):\n    pass\n\nimport json\nnums = json.loads(input())\nprint(find_min(nums))",
      testCases: JSON.stringify([
        { input: "[3,4,5,1,2]", expected: "1" },
        { input: "[4,5,6,7,0,1,2]", expected: "0" },
        { input: "[11,13,15,17]", expected: "11" },
      ]),
      solutionApproach: "Binary search: compare mid with right. If mid > right, min is in right half. Else left half. O(log n).",
      companyTags: JSON.stringify(["Amazon", "Google", "Microsoft"]),
    },
    {
      slug: "maximum-product-subarray",
      title: "Maximum Product Subarray",
      description: "Given an integer array `nums`, find a contiguous non-empty subarray that has the largest product.\n\n**Example:**\n```\nInput: nums = [2,3,-2,4]\nOutput: 6 ([2,3])\n```",
      difficulty: "medium",
      category: "arrays",
      starterCode: "def max_product(nums):\n    pass\n\nimport json\nnums = json.loads(input())\nprint(max_product(nums))",
      testCases: JSON.stringify([
        { input: "[2,3,-2,4]", expected: "6" },
        { input: "[-2,0,-1]", expected: "0" },
        { input: "[-2,3,-4]", expected: "24" },
      ]),
      solutionApproach: "Track both max and min product at each position (negative * negative = positive). O(n).",
      companyTags: JSON.stringify(["Amazon", "Google", "Microsoft"]),
    },
    {
      slug: "subarray-sum-equals-k",
      title: "Subarray Sum Equals K",
      description: "Given an array of integers `nums` and an integer `k`, return the total number of subarrays whose sum equals `k`.\n\n**Example:**\n```\nInput: nums = [1,1,1], k = 2\nOutput: 2\n```",
      difficulty: "medium",
      category: "arrays",
      starterCode: "def subarray_sum(nums, k):\n    pass\n\nimport json\nnums = json.loads(input())\nk = int(input())\nprint(subarray_sum(nums, k))",
      testCases: JSON.stringify([
        { input: "[1,1,1]\n2", expected: "2" },
        { input: "[1,2,3]\n3", expected: "2" },
      ]),
      solutionApproach: "Prefix sum + hash map. For each prefix sum, check if (prefix_sum - k) exists in map. O(n).",
      companyTags: JSON.stringify(["Google", "Meta", "Amazon"]),
    },

    // ═══════════════════════════════════════════════════════
    // STRINGS — 8 new problems
    // ═══════════════════════════════════════════════════════
    {
      slug: "valid-anagram",
      title: "Valid Anagram",
      description: "Given two strings `s` and `t`, return `True` if `t` is an anagram of `s`.\n\n**Example:**\n```\nInput: s = \"anagram\", t = \"nagaram\"\nOutput: True\n```",
      difficulty: "easy",
      category: "strings",
      starterCode: "def is_anagram(s, t):\n    pass\n\ns = input().strip()\nt = input().strip()\nprint(is_anagram(s, t))",
      testCases: JSON.stringify([
        { input: "anagram\nnagaram", expected: "True" },
        { input: "rat\ncar", expected: "False" },
      ]),
      solutionApproach: "Count character frequencies. Compare counts. O(n) time, O(1) space (26 letters).",
      companyTags: JSON.stringify(["Amazon", "Google", "Microsoft"]),
    },
    {
      slug: "first-unique-character",
      title: "First Unique Character in a String",
      description: "Given a string `s`, find the first non-repeating character and return its index. If none, return -1.\n\n**Example:**\n```\nInput: s = \"leetcode\"\nOutput: 0\n```",
      difficulty: "easy",
      category: "strings",
      starterCode: "def first_uniq_char(s):\n    pass\n\ns = input().strip()\nprint(first_uniq_char(s))",
      testCases: JSON.stringify([
        { input: "leetcode", expected: "0" },
        { input: "loveleetcode", expected: "2" },
        { input: "aabb", expected: "-1" },
      ]),
      solutionApproach: "Count frequencies, then iterate to find first with count 1. O(n) time, O(1) space.",
      companyTags: JSON.stringify(["Amazon", "Google", "Apple"]),
    },
    {
      slug: "longest-common-prefix",
      title: "Longest Common Prefix",
      description: "Find the longest common prefix string amongst an array of strings.\n\n**Example:**\n```\nInput: strs = [\"flower\",\"flow\",\"flight\"]\nOutput: \"fl\"\n```",
      difficulty: "easy",
      category: "strings",
      starterCode: "def longest_common_prefix(strs):\n    pass\n\nimport json\nstrs = json.loads(input())\nprint(longest_common_prefix(strs))",
      testCases: JSON.stringify([
        { input: '["flower","flow","flight"]', expected: "fl" },
        { input: '["dog","racecar","car"]', expected: "" },
      ]),
      solutionApproach: "Vertical scanning: compare character by character across all strings. O(S) where S is sum of all characters.",
      companyTags: JSON.stringify(["Amazon", "Google", "Microsoft"]),
    },
    {
      slug: "string-to-integer-atoi",
      title: "String to Integer (atoi)",
      description: "Implement `atoi` which converts a string to an integer. Handle whitespace, sign, digits, and overflow.\n\n**Example:**\n```\nInput: s = \"   -42\"\nOutput: -42\n```\n\nClamp to [-2³¹, 2³¹ - 1] on overflow.",
      difficulty: "medium",
      category: "strings",
      starterCode: "def my_atoi(s):\n    pass\n\ns = input()\nprint(my_atoi(s))",
      testCases: JSON.stringify([
        { input: "   -42", expected: "-42" },
        { input: "4193 with words", expected: "4193" },
        { input: "words and 987", expected: "0" },
      ]),
      solutionApproach: "State machine: skip whitespace, read sign, read digits, handle overflow. O(n).",
      companyTags: JSON.stringify(["Amazon", "Microsoft", "Goldman Sachs"]),
    },
    {
      slug: "count-and-say",
      title: "Count and Say",
      description: "The count-and-say sequence is defined by: `countAndSay(1) = \"1\"`, `countAndSay(n)` is the way you would describe `countAndSay(n-1)`.\n\n**Example:**\n```\ncountAndSay(1) = \"1\"\ncountAndSay(2) = \"11\" (one 1)\ncountAndSay(3) = \"21\" (two 1s)\ncountAndSay(4) = \"1211\" (one 2, one 1)\n```",
      difficulty: "medium",
      category: "strings",
      starterCode: "def count_and_say(n):\n    pass\n\nn = int(input())\nprint(count_and_say(n))",
      testCases: JSON.stringify([
        { input: "1", expected: "1" },
        { input: "4", expected: "1211" },
        { input: "5", expected: "111221" },
      ]),
      solutionApproach: "Build iteratively. For each step, group consecutive same digits and describe 'count + digit'. O(2^n) due to exponential growth.",
      companyTags: JSON.stringify(["Meta", "Amazon"]),
    },
    {
      slug: "zigzag-conversion",
      title: "Zigzag Conversion",
      description: "Write the string in a zigzag pattern on a given number of rows, then read line by line.\n\n**Example:**\n```\nInput: s = \"PAYPALISHIRING\", numRows = 3\nP   A   H   N\nA P L S I I G\nY   I   R\nOutput: \"PAHNAPLSIIGYIR\"\n```",
      difficulty: "medium",
      category: "strings",
      starterCode: "def convert(s, num_rows):\n    pass\n\ns = input().strip()\nn = int(input())\nprint(convert(s, n))",
      testCases: JSON.stringify([
        { input: "PAYPALISHIRING\n3", expected: "PAHNAPLSIIGYIR" },
        { input: "PAYPALISHIRING\n4", expected: "PINALSIGYAHRPI" },
        { input: "A\n1", expected: "A" },
      ]),
      solutionApproach: "Create numRows strings. Iterate through s, distributing chars by bouncing index. O(n).",
      companyTags: JSON.stringify(["Amazon"]),
    },
    {
      slug: "encode-decode-strings",
      title: "Encode and Decode Strings",
      description: "Design an algorithm to encode a list of strings to a single string and decode it back.\n\n**Example:**\n```\nInput: [\"hello\",\"world\"]\nEncoded: \"5#hello5#world\"\nDecoded: [\"hello\",\"world\"]\n```",
      difficulty: "medium",
      category: "strings",
      starterCode: "def encode(strs):\n    pass\n\ndef decode(s):\n    pass\n\nimport json\nstrs = json.loads(input())\nencoded = encode(strs)\nresult = decode(encoded)\nprint(json.dumps(result))",
      testCases: JSON.stringify([
        { input: '["hello","world"]', expected: '["hello", "world"]' },
        { input: '[""]', expected: '[""]' },
        { input: '["a","b","c"]', expected: '["a", "b", "c"]' },
      ]),
      solutionApproach: "Length-delimited encoding: for each string, store length + delimiter + string. O(n).",
      companyTags: JSON.stringify(["Google", "Meta"]),
    },
    {
      slug: "minimum-remove-valid-parens",
      title: "Minimum Remove to Make Valid Parentheses",
      description: "Given a string `s` of `(`, `)` and lowercase letters, remove minimum parentheses to make it valid.\n\n**Example:**\n```\nInput: s = \"lee(t(c)o)de)\"\nOutput: \"lee(t(c)o)de\"\n```",
      difficulty: "medium",
      category: "strings",
      starterCode: "def min_remove(s):\n    pass\n\ns = input().strip()\nprint(min_remove(s))",
      testCases: JSON.stringify([
        { input: "lee(t(c)o)de)", expected: "lee(t(c)o)de" },
        { input: "a)b(c)d", expected: "ab(c)d" },
        { input: "))((" , expected: "" },
      ]),
      solutionApproach: "Two passes: left-to-right remove extra ')'. Right-to-left remove extra '('. O(n).",
      companyTags: JSON.stringify(["Meta", "Amazon", "Google"]),
    },

    // ═══════════════════════════════════════════════════════
    // DYNAMIC PROGRAMMING — 10 new problems
    // ═══════════════════════════════════════════════════════
    {
      slug: "unique-paths",
      title: "Unique Paths",
      description: "A robot is at the top-left corner of an `m x n` grid. It can only move right or down. How many unique paths to the bottom-right?\n\n**Example:**\n```\nInput: m = 3, n = 7\nOutput: 28\n```",
      difficulty: "medium",
      category: "dynamic-programming",
      starterCode: "def unique_paths(m, n):\n    pass\n\nm = int(input())\nn = int(input())\nprint(unique_paths(m, n))",
      testCases: JSON.stringify([
        { input: "3\n7", expected: "28" },
        { input: "3\n2", expected: "3" },
      ]),
      solutionApproach: "DP: dp[i][j] = dp[i-1][j] + dp[i][j-1]. Or math: C(m+n-2, m-1). O(m*n).",
      companyTags: JSON.stringify(["Amazon", "Google", "Microsoft"]),
    },
    {
      slug: "decode-ways",
      title: "Decode Ways",
      description: "A message containing `A-Z` is encoded as `1-26`. Given a string of digits, return the number of ways to decode it.\n\n**Example:**\n```\nInput: s = \"226\"\nOutput: 3 (\"BZ\"=2,26 | \"VF\"=22,6 | \"BBF\"=2,2,6)\n```",
      difficulty: "medium",
      category: "dynamic-programming",
      starterCode: "def num_decodings(s):\n    pass\n\ns = input().strip()\nprint(num_decodings(s))",
      testCases: JSON.stringify([
        { input: "12", expected: "2" },
        { input: "226", expected: "3" },
        { input: "06", expected: "0" },
      ]),
      solutionApproach: "DP: dp[i] = dp[i-1] (if valid single digit) + dp[i-2] (if valid two digits 10-26). O(n).",
      companyTags: JSON.stringify(["Amazon", "Google", "Meta", "Microsoft"]),
    },
    {
      slug: "longest-common-subsequence",
      title: "Longest Common Subsequence",
      description: "Given two strings `text1` and `text2`, return the length of their longest common subsequence.\n\n**Example:**\n```\nInput: text1 = \"abcde\", text2 = \"ace\"\nOutput: 3 (\"ace\")\n```",
      difficulty: "medium",
      category: "dynamic-programming",
      starterCode: "def lcs(text1, text2):\n    pass\n\ntext1 = input().strip()\ntext2 = input().strip()\nprint(lcs(text1, text2))",
      testCases: JSON.stringify([
        { input: "abcde\nace", expected: "3" },
        { input: "abc\nabc", expected: "3" },
        { input: "abc\ndef", expected: "0" },
      ]),
      solutionApproach: "2D DP: if chars match dp[i][j]=dp[i-1][j-1]+1, else max(dp[i-1][j], dp[i][j-1]). O(m*n).",
      companyTags: JSON.stringify(["Amazon", "Google", "Microsoft"]),
    },
    {
      slug: "edit-distance",
      title: "Edit Distance",
      description: "Given two strings `word1` and `word2`, return the minimum number of operations (insert, delete, replace) to convert `word1` to `word2`.\n\n**Example:**\n```\nInput: word1 = \"horse\", word2 = \"ros\"\nOutput: 3\n```",
      difficulty: "hard",
      category: "dynamic-programming",
      starterCode: "def min_distance(word1, word2):\n    pass\n\nword1 = input().strip()\nword2 = input().strip()\nprint(min_distance(word1, word2))",
      testCases: JSON.stringify([
        { input: "horse\nros", expected: "3" },
        { input: "intention\nexecution", expected: "5" },
      ]),
      solutionApproach: "2D DP: if chars match dp[i][j]=dp[i-1][j-1], else 1 + min(insert, delete, replace). O(m*n).",
      companyTags: JSON.stringify(["Amazon", "Google", "Microsoft"]),
    },
    {
      slug: "partition-equal-subset-sum",
      title: "Partition Equal Subset Sum",
      description: "Given a non-empty array of positive integers, determine if it can be partitioned into two subsets with equal sum.\n\n**Example:**\n```\nInput: nums = [1,5,11,5]\nOutput: True ([1,5,5] and [11])\n```",
      difficulty: "medium",
      category: "dynamic-programming",
      starterCode: "def can_partition(nums):\n    pass\n\nimport json\nnums = json.loads(input())\nprint(can_partition(nums))",
      testCases: JSON.stringify([
        { input: "[1,5,11,5]", expected: "True" },
        { input: "[1,2,3,5]", expected: "False" },
      ]),
      solutionApproach: "0/1 knapsack. Target = sum/2. DP: dp[j] = can we make sum j? O(n * sum).",
      companyTags: JSON.stringify(["Amazon", "Google", "Meta"]),
    },
    {
      slug: "min-cost-climbing-stairs",
      title: "Min Cost Climbing Stairs",
      description: "Given an array `cost` where `cost[i]` is the cost of step `i`, you can start from step 0 or 1. Pay the cost then climb 1 or 2 steps. Find minimum cost to reach the top.\n\n**Example:**\n```\nInput: cost = [10,15,20]\nOutput: 15 (start at index 1, pay 15, climb 2)\n```",
      difficulty: "easy",
      category: "dynamic-programming",
      starterCode: "def min_cost(cost):\n    pass\n\nimport json\ncost = json.loads(input())\nprint(min_cost(cost))",
      testCases: JSON.stringify([
        { input: "[10,15,20]", expected: "15" },
        { input: "[1,100,1,1,1,100,1,1,100,1]", expected: "6" },
      ]),
      solutionApproach: "DP: dp[i] = cost[i] + min(dp[i-1], dp[i-2]). Answer = min(dp[-1], dp[-2]). O(n).",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },
    {
      slug: "coin-change-ii",
      title: "Coin Change II",
      description: "Given coins and an amount, return the number of combinations that make up that amount.\n\n**Example:**\n```\nInput: amount = 5, coins = [1,2,5]\nOutput: 4 (5, 2+2+1, 2+1+1+1, 1+1+1+1+1)\n```",
      difficulty: "medium",
      category: "dynamic-programming",
      starterCode: "def change(amount, coins):\n    pass\n\nimport json\namount = int(input())\ncoins = json.loads(input())\nprint(change(amount, coins))",
      testCases: JSON.stringify([
        { input: "5\n[1,2,5]", expected: "4" },
        { input: "3\n[2]", expected: "0" },
        { input: "10\n[10]", expected: "1" },
      ]),
      solutionApproach: "Unbounded knapsack DP. For each coin, iterate amounts. dp[j] += dp[j-coin]. O(amount * coins).",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },
    {
      slug: "palindromic-substrings",
      title: "Palindromic Substrings",
      description: "Given a string `s`, return the number of palindromic substrings.\n\n**Example:**\n```\nInput: s = \"abc\"\nOutput: 3 (\"a\", \"b\", \"c\")\n```\n```\nInput: s = \"aaa\"\nOutput: 6 (\"a\",\"a\",\"a\",\"aa\",\"aa\",\"aaa\")\n```",
      difficulty: "medium",
      category: "dynamic-programming",
      starterCode: "def count_substrings(s):\n    pass\n\ns = input().strip()\nprint(count_substrings(s))",
      testCases: JSON.stringify([
        { input: "abc", expected: "3" },
        { input: "aaa", expected: "6" },
      ]),
      solutionApproach: "Expand around center for each character and each pair of characters. O(n²).",
      companyTags: JSON.stringify(["Amazon", "Meta", "Google"]),
    },
    {
      slug: "maximal-square",
      title: "Maximal Square",
      description: "Given an `m x n` binary matrix filled with `0`s and `1`s, find the largest square containing only `1`s and return its area.\n\n**Example:**\n```\nInput: matrix = [[\"1\",\"0\",\"1\",\"0\",\"0\"],[\"1\",\"0\",\"1\",\"1\",\"1\"],[\"1\",\"1\",\"1\",\"1\",\"1\"],[\"1\",\"0\",\"0\",\"1\",\"0\"]]\nOutput: 4\n```",
      difficulty: "medium",
      category: "dynamic-programming",
      starterCode: "def maximal_square(matrix):\n    pass\n\nimport json\nmatrix = json.loads(input())\nprint(maximal_square(matrix))",
      testCases: JSON.stringify([
        { input: '[["1","0","1","0","0"],["1","0","1","1","1"],["1","1","1","1","1"],["1","0","0","1","0"]]', expected: "4" },
        { input: '[["0","1"],["1","0"]]', expected: "1" },
      ]),
      solutionApproach: "DP: dp[i][j] = min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1]) + 1 if cell is '1'. Track max side. O(m*n).",
      companyTags: JSON.stringify(["Amazon", "Google", "Apple"]),
    },
    {
      slug: "target-sum",
      title: "Target Sum",
      description: "Given an array `nums` and a target, assign `+` or `-` to each number to reach the target. Return the number of ways.\n\n**Example:**\n```\nInput: nums = [1,1,1,1,1], target = 3\nOutput: 5\n```",
      difficulty: "medium",
      category: "dynamic-programming",
      starterCode: "def find_target_sum_ways(nums, target):\n    pass\n\nimport json\nnums = json.loads(input())\ntarget = int(input())\nprint(find_target_sum_ways(nums, target))",
      testCases: JSON.stringify([
        { input: "[1,1,1,1,1]\n3", expected: "5" },
        { input: "[1]\n1", expected: "1" },
      ]),
      solutionApproach: "DP with offset or hash map of sums. Or reduce to subset sum problem. O(n * sum).",
      companyTags: JSON.stringify(["Meta", "Amazon", "Google"]),
    },

    // ═══════════════════════════════════════════════════════
    // GRAPHS — 8 new problems
    // ═══════════════════════════════════════════════════════
    {
      slug: "pacific-atlantic-water-flow",
      title: "Pacific Atlantic Water Flow",
      description: "Given an `m x n` matrix of heights, water can flow to adjacent cells with equal or lower height. Find all cells that can reach both the Pacific (top/left) and Atlantic (bottom/right) oceans.\n\n**Example:**\n```\nInput: heights = [[1,2,2,3,5],[3,2,3,4,4],[2,4,5,3,1],[6,7,1,4,5],[5,1,1,2,4]]\nOutput: [[0,4],[1,3],[1,4],[2,2],[3,0],[3,1],[4,0]]\n```",
      difficulty: "medium",
      category: "graphs",
      starterCode: "def pacific_atlantic(heights):\n    pass\n\nimport json\nheights = json.loads(input())\nresult = pacific_atlantic(heights)\nprint(json.dumps(sorted(result)))",
      testCases: JSON.stringify([
        { input: "[[1,2,2,3,5],[3,2,3,4,4],[2,4,5,3,1],[6,7,1,4,5],[5,1,1,2,4]]", expected: "[[0, 4], [1, 3], [1, 4], [2, 2], [3, 0], [3, 1], [4, 0]]" },
      ]),
      solutionApproach: "BFS/DFS from ocean borders. Two visited sets. Answer = intersection. O(m*n).",
      companyTags: JSON.stringify(["Amazon", "Google", "Meta"]),
    },
    {
      slug: "rotting-oranges",
      title: "Rotting Oranges",
      description: "In a grid, `0` = empty, `1` = fresh orange, `2` = rotten. Each minute, adjacent fresh oranges rot. Return minutes until no fresh oranges, or -1 if impossible.\n\n**Example:**\n```\nInput: grid = [[2,1,1],[1,1,0],[0,1,1]]\nOutput: 4\n```",
      difficulty: "medium",
      category: "graphs",
      starterCode: "def oranges_rotting(grid):\n    pass\n\nimport json\ngrid = json.loads(input())\nprint(oranges_rotting(grid))",
      testCases: JSON.stringify([
        { input: "[[2,1,1],[1,1,0],[0,1,1]]", expected: "4" },
        { input: "[[2,1,1],[0,1,1],[1,0,1]]", expected: "-1" },
        { input: "[[0,2]]", expected: "0" },
      ]),
      solutionApproach: "Multi-source BFS from all rotten oranges. Count levels. Check if fresh remain. O(m*n).",
      companyTags: JSON.stringify(["Amazon", "Google", "Microsoft"]),
    },
    {
      slug: "walls-and-gates",
      title: "Walls and Gates",
      description: "Given a grid where `-1` = wall, `0` = gate, `INF` = empty room, fill each empty room with its distance to the nearest gate.\n\n**Example:**\n```\nInput: [[2147483647,-1,0,2147483647],[2147483647,2147483647,2147483647,-1],[2147483647,-1,2147483647,-1],[0,-1,2147483647,2147483647]]\nOutput: [[3,-1,0,1],[2,2,1,-1],[1,-1,2,-1],[0,-1,3,4]]\n```",
      difficulty: "medium",
      category: "graphs",
      starterCode: "def walls_and_gates(rooms):\n    pass\n\nimport json\nrooms = json.loads(input())\nwalls_and_gates(rooms)\nprint(json.dumps(rooms))",
      testCases: JSON.stringify([
        { input: "[[2147483647,-1,0,2147483647],[2147483647,2147483647,2147483647,-1],[2147483647,-1,2147483647,-1],[0,-1,2147483647,2147483647]]", expected: "[[3, -1, 0, 1], [2, 2, 1, -1], [1, -1, 2, -1], [0, -1, 3, 4]]" },
      ]),
      solutionApproach: "Multi-source BFS from all gates simultaneously. O(m*n).",
      companyTags: JSON.stringify(["Meta", "Amazon", "Google"]),
    },
    {
      slug: "graph-valid-tree",
      title: "Graph Valid Tree",
      description: "Given `n` nodes labeled `0` to `n-1` and a list of undirected edges, check if these edges form a valid tree (connected, no cycles).\n\n**Example:**\n```\nInput: n = 5, edges = [[0,1],[0,2],[0,3],[1,4]]\nOutput: True\n```",
      difficulty: "medium",
      category: "graphs",
      starterCode: "def valid_tree(n, edges):\n    pass\n\nimport json\nn = int(input())\nedges = json.loads(input())\nprint(valid_tree(n, edges))",
      testCases: JSON.stringify([
        { input: "5\n[[0,1],[0,2],[0,3],[1,4]]", expected: "True" },
        { input: "5\n[[0,1],[1,2],[2,3],[1,3],[1,4]]", expected: "False" },
      ]),
      solutionApproach: "Union-Find or DFS. Tree: connected + no cycles. Must have exactly n-1 edges. O(V+E).",
      companyTags: JSON.stringify(["Google", "Meta", "Amazon"]),
    },
    {
      slug: "number-connected-components",
      title: "Number of Connected Components",
      description: "Given `n` nodes and a list of undirected edges, return the number of connected components.\n\n**Example:**\n```\nInput: n = 5, edges = [[0,1],[1,2],[3,4]]\nOutput: 2\n```",
      difficulty: "medium",
      category: "graphs",
      starterCode: "def count_components(n, edges):\n    pass\n\nimport json\nn = int(input())\nedges = json.loads(input())\nprint(count_components(n, edges))",
      testCases: JSON.stringify([
        { input: "5\n[[0,1],[1,2],[3,4]]", expected: "2" },
        { input: "5\n[[0,1],[1,2],[2,3],[3,4]]", expected: "1" },
      ]),
      solutionApproach: "Union-Find: start with n components, each union reduces by 1. Or DFS/BFS counting. O(V+E).",
      companyTags: JSON.stringify(["Google", "Meta", "Amazon"]),
    },
    {
      slug: "network-delay-time",
      title: "Network Delay Time",
      description: "There are `n` network nodes. Given travel times as `[u, v, w]`, send a signal from node `k`. Return the time for all nodes to receive it. If impossible, return -1.\n\n**Example:**\n```\nInput: times = [[2,1,1],[2,3,1],[3,4,1]], n = 4, k = 2\nOutput: 2\n```",
      difficulty: "medium",
      category: "graphs",
      starterCode: "def network_delay(times, n, k):\n    pass\n\nimport json\ntimes = json.loads(input())\nn = int(input())\nk = int(input())\nprint(network_delay(times, n, k))",
      testCases: JSON.stringify([
        { input: "[[2,1,1],[2,3,1],[3,4,1]]\n4\n2", expected: "2" },
        { input: "[[1,2,1]]\n2\n1", expected: "1" },
        { input: "[[1,2,1]]\n2\n2", expected: "-1" },
      ]),
      solutionApproach: "Dijkstra's algorithm from node k. Answer = max distance to any reachable node. O((V+E) log V).",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },
    {
      slug: "surrounded-regions",
      title: "Surrounded Regions",
      description: "Given an `m x n` board of `X` and `O`, capture all regions of `O` that are completely surrounded by `X` (flip to `X`). Border-connected `O`s are NOT captured.\n\n**Example:**\n```\nInput: [[\"X\",\"X\",\"X\",\"X\"],[\"X\",\"O\",\"O\",\"X\"],[\"X\",\"X\",\"O\",\"X\"],[\"X\",\"O\",\"X\",\"X\"]]\nOutput: [[\"X\",\"X\",\"X\",\"X\"],[\"X\",\"X\",\"X\",\"X\"],[\"X\",\"X\",\"X\",\"X\"],[\"X\",\"O\",\"X\",\"X\"]]\n```",
      difficulty: "medium",
      category: "graphs",
      starterCode: "def solve(board):\n    pass\n\nimport json\nboard = json.loads(input())\nsolve(board)\nprint(json.dumps(board))",
      testCases: JSON.stringify([
        { input: '[["X","X","X","X"],["X","O","O","X"],["X","X","O","X"],["X","O","X","X"]]', expected: '[["X", "X", "X", "X"], ["X", "X", "X", "X"], ["X", "X", "X", "X"], ["X", "O", "X", "X"]]' },
      ]),
      solutionApproach: "DFS/BFS from border O's to mark safe. Then flip all remaining O's. O(m*n).",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },
    {
      slug: "alien-dictionary",
      title: "Alien Dictionary",
      description: "Given a sorted list of words in an alien language, derive the order of characters.\n\n**Example:**\n```\nInput: words = [\"wrt\",\"wrf\",\"er\",\"ett\",\"rftt\"]\nOutput: \"wertf\"\n```\n\nReturn empty string if invalid ordering.",
      difficulty: "hard",
      category: "graphs",
      starterCode: "def alien_order(words):\n    pass\n\nimport json\nwords = json.loads(input())\nprint(alien_order(words))",
      testCases: JSON.stringify([
        { input: '["wrt","wrf","er","ett","rftt"]', expected: "wertf" },
        { input: '["z","x"]', expected: "zx" },
        { input: '["z","x","z"]', expected: "" },
      ]),
      solutionApproach: "Build directed graph from adjacent word comparisons. Topological sort. Detect cycles. O(C) where C is total chars.",
      companyTags: JSON.stringify(["Meta", "Google", "Amazon", "Microsoft"]),
    },

    // ═══════════════════════════════════════════════════════
    // HASH MAPS — 5 new problems
    // ═══════════════════════════════════════════════════════
    {
      slug: "two-sum-ii-sorted",
      title: "Two Sum II - Input Array Is Sorted",
      description: "Given a 1-indexed sorted array, find two numbers that add up to target. Return their indices.\n\n**Example:**\n```\nInput: numbers = [2,7,11,15], target = 9\nOutput: [1,2]\n```",
      difficulty: "medium",
      category: "hash-maps",
      starterCode: "def two_sum_ii(numbers, target):\n    pass\n\nimport json\nnumbers = json.loads(input())\ntarget = int(input())\nprint(json.dumps(two_sum_ii(numbers, target)))",
      testCases: JSON.stringify([
        { input: "[2,7,11,15]\n9", expected: "[1, 2]" },
        { input: "[2,3,4]\n6", expected: "[1, 3]" },
        { input: "[-1,0]\n-1", expected: "[1, 2]" },
      ]),
      solutionApproach: "Two pointers from both ends. If sum < target, move left. If sum > target, move right. O(n) time, O(1) space.",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },
    {
      slug: "isomorphic-strings",
      title: "Isomorphic Strings",
      description: "Given two strings `s` and `t`, determine if they are isomorphic. Two strings are isomorphic if characters in `s` can be replaced to get `t` (one-to-one mapping).\n\n**Example:**\n```\nInput: s = \"egg\", t = \"add\"\nOutput: True\n```",
      difficulty: "easy",
      category: "hash-maps",
      starterCode: "def is_isomorphic(s, t):\n    pass\n\ns = input().strip()\nt = input().strip()\nprint(is_isomorphic(s, t))",
      testCases: JSON.stringify([
        { input: "egg\nadd", expected: "True" },
        { input: "foo\nbar", expected: "False" },
        { input: "paper\ntitle", expected: "True" },
      ]),
      solutionApproach: "Two hash maps for bidirectional mapping. Check consistency at each char. O(n).",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },
    {
      slug: "happy-number",
      title: "Happy Number",
      description: "A number is happy if replacing it by the sum of squares of its digits eventually reaches 1. If it loops forever, it's not happy.\n\n**Example:**\n```\nInput: n = 19\nOutput: True (1² + 9² = 82 → 8² + 2² = 68 → ... → 1)\n```",
      difficulty: "easy",
      category: "hash-maps",
      starterCode: "def is_happy(n):\n    pass\n\nn = int(input())\nprint(is_happy(n))",
      testCases: JSON.stringify([
        { input: "19", expected: "True" },
        { input: "2", expected: "False" },
      ]),
      solutionApproach: "Use a set to detect cycles. Or Floyd's algorithm (slow/fast pointer). O(log n) per step.",
      companyTags: JSON.stringify(["Amazon", "Apple"]),
    },
    {
      slug: "intersection-two-arrays-ii",
      title: "Intersection of Two Arrays II",
      description: "Given two integer arrays, return an array of their intersection. Each element in the result must appear as many times as it shows in both arrays.\n\n**Example:**\n```\nInput: nums1 = [1,2,2,1], nums2 = [2,2]\nOutput: [2,2]\n```",
      difficulty: "easy",
      category: "hash-maps",
      starterCode: "def intersect(nums1, nums2):\n    pass\n\nimport json\nnums1 = json.loads(input())\nnums2 = json.loads(input())\nprint(json.dumps(sorted(intersect(nums1, nums2))))",
      testCases: JSON.stringify([
        { input: "[1,2,2,1]\n[2,2]", expected: "[2, 2]" },
        { input: "[4,9,5]\n[9,4,9,8,4]", expected: "[4, 9]" },
      ]),
      solutionApproach: "Counter/hash map for smaller array. Iterate larger, decrement counts. O(n+m).",
      companyTags: JSON.stringify(["Amazon", "Google", "Meta"]),
    },
    {
      slug: "ransom-note",
      title: "Ransom Note",
      description: "Given two strings `ransomNote` and `magazine`, return `True` if `ransomNote` can be constructed from `magazine` characters.\n\n**Example:**\n```\nInput: ransomNote = \"aa\", magazine = \"aab\"\nOutput: True\n```",
      difficulty: "easy",
      category: "hash-maps",
      starterCode: "def can_construct(ransom_note, magazine):\n    pass\n\nransom_note = input().strip()\nmagazine = input().strip()\nprint(can_construct(ransom_note, magazine))",
      testCases: JSON.stringify([
        { input: "a\nb", expected: "False" },
        { input: "aa\naab", expected: "True" },
      ]),
      solutionApproach: "Count chars in magazine. Check if ransom note chars are available. O(n+m).",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },

    // ═══════════════════════════════════════════════════════
    // LINKED LISTS — 5 new problems
    // ═══════════════════════════════════════════════════════
    {
      slug: "reverse-linked-list-v2",
      title: "Reverse Linked List",
      description: "Given a linked list (as array), reverse it.\n\n**Example:**\n```\nInput: head = [1,2,3,4,5]\nOutput: [5,4,3,2,1]\n```",
      difficulty: "easy",
      category: "linked-lists",
      starterCode: "def reverse_list(head):\n    pass\n\nimport json\nhead = json.loads(input())\nprint(json.dumps(reverse_list(head)))",
      testCases: JSON.stringify([
        { input: "[1,2,3,4,5]", expected: "[5, 4, 3, 2, 1]" },
        { input: "[1,2]", expected: "[2, 1]" },
        { input: "[]", expected: "[]" },
      ]),
      solutionApproach: "Three pointers: prev, curr, next. Iterate and reverse links. O(n) time, O(1) space.",
      companyTags: JSON.stringify(["Amazon", "Microsoft", "Apple"]),
    },
    {
      slug: "remove-nth-from-end",
      title: "Remove Nth Node From End of List",
      description: "Given a linked list (as array), remove the nth node from the end.\n\n**Example:**\n```\nInput: head = [1,2,3,4,5], n = 2\nOutput: [1,2,3,5]\n```",
      difficulty: "medium",
      category: "linked-lists",
      starterCode: "def remove_nth_from_end(head, n):\n    pass\n\nimport json\nhead = json.loads(input())\nn = int(input())\nprint(json.dumps(remove_nth_from_end(head, n)))",
      testCases: JSON.stringify([
        { input: "[1,2,3,4,5]\n2", expected: "[1, 2, 3, 5]" },
        { input: "[1]\n1", expected: "[]" },
        { input: "[1,2]\n1", expected: "[1]" },
      ]),
      solutionApproach: "Two pointers with n gap. When fast reaches end, slow is at node before target. O(n), one pass.",
      companyTags: JSON.stringify(["Amazon", "Meta", "Google"]),
    },
    {
      slug: "reorder-list",
      title: "Reorder List",
      description: "Given a linked list L0 → L1 → … → Ln, reorder it to L0 → Ln → L1 → Ln−1 → …\n\nUse array representation.\n\n**Example:**\n```\nInput: head = [1,2,3,4]\nOutput: [1,4,2,3]\n```",
      difficulty: "medium",
      category: "linked-lists",
      starterCode: "def reorder_list(head):\n    pass\n\nimport json\nhead = json.loads(input())\nreorder_list(head)\nprint(json.dumps(head))",
      testCases: JSON.stringify([
        { input: "[1,2,3,4]", expected: "[1, 4, 2, 3]" },
        { input: "[1,2,3,4,5]", expected: "[1, 5, 2, 4, 3]" },
      ]),
      solutionApproach: "Find middle, reverse second half, merge alternately. O(n) time, O(1) space.",
      companyTags: JSON.stringify(["Amazon", "Meta", "Google"]),
    },
    {
      slug: "add-two-numbers",
      title: "Add Two Numbers",
      description: "Two numbers stored as reversed linked lists (arrays). Add them and return result.\n\n**Example:**\n```\nInput: l1 = [2,4,3], l2 = [5,6,4]\nOutput: [7,0,8] (342 + 465 = 807)\n```",
      difficulty: "medium",
      category: "linked-lists",
      starterCode: "def add_two_numbers(l1, l2):\n    pass\n\nimport json\nl1 = json.loads(input())\nl2 = json.loads(input())\nprint(json.dumps(add_two_numbers(l1, l2)))",
      testCases: JSON.stringify([
        { input: "[2,4,3]\n[5,6,4]", expected: "[7, 0, 8]" },
        { input: "[0]\n[0]", expected: "[0]" },
        { input: "[9,9,9,9,9,9,9]\n[9,9,9,9]", expected: "[8, 9, 9, 9, 0, 0, 0, 1]" },
      ]),
      solutionApproach: "Iterate both lists with carry. Sum = l1.val + l2.val + carry. New digit = sum % 10, carry = sum // 10. O(max(m,n)).",
      companyTags: JSON.stringify(["Amazon", "Google", "Microsoft", "Meta"]),
    },
    {
      slug: "middle-linked-list",
      title: "Middle of the Linked List",
      description: "Given a linked list (as array), return the middle node's value. If two middles, return second.\n\n**Example:**\n```\nInput: head = [1,2,3,4,5]\nOutput: 3\n```",
      difficulty: "easy",
      category: "linked-lists",
      starterCode: "def middle_node(head):\n    pass\n\nimport json\nhead = json.loads(input())\nprint(middle_node(head))",
      testCases: JSON.stringify([
        { input: "[1,2,3,4,5]", expected: "3" },
        { input: "[1,2,3,4,5,6]", expected: "4" },
      ]),
      solutionApproach: "Slow and fast pointers. Fast moves 2 steps, slow moves 1. When fast reaches end, slow is at middle. O(n).",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },

    // ═══════════════════════════════════════════════════════
    // TREES — 8 new problems
    // ═══════════════════════════════════════════════════════
    {
      slug: "same-tree",
      title: "Same Tree",
      description: "Given two binary trees (as arrays), check if they are structurally identical and have the same node values.\n\n**Example:**\n```\nInput: p = [1,2,3], q = [1,2,3]\nOutput: True\n```",
      difficulty: "easy",
      category: "trees",
      starterCode: "def is_same_tree(p, q):\n    pass\n\nimport json\np = json.loads(input())\nq = json.loads(input())\nprint(is_same_tree(p, q))",
      testCases: JSON.stringify([
        { input: "[1,2,3]\n[1,2,3]", expected: "True" },
        { input: "[1,2]\n[1,null,2]", expected: "False" },
      ]),
      solutionApproach: "Recursive comparison of values and structure. O(min(n,m)).",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },
    {
      slug: "subtree-of-another-tree",
      title: "Subtree of Another Tree",
      description: "Given two binary trees `root` and `subRoot` (as arrays), check if `subRoot` is a subtree of `root`.\n\n**Example:**\n```\nInput: root = [3,4,5,1,2], subRoot = [4,1,2]\nOutput: True\n```",
      difficulty: "easy",
      category: "trees",
      starterCode: "def is_subtree(root, sub_root):\n    pass\n\nimport json\nroot = json.loads(input())\nsub_root = json.loads(input())\nprint(is_subtree(root, sub_root))",
      testCases: JSON.stringify([
        { input: "[3,4,5,1,2]\n[4,1,2]", expected: "True" },
        { input: "[3,4,5,1,2,null,null,null,null,0]\n[4,1,2]", expected: "False" },
      ]),
      solutionApproach: "At each node, check if current subtree matches. O(m*n).",
      companyTags: JSON.stringify(["Amazon", "Google", "Meta"]),
    },
    {
      slug: "lowest-common-ancestor-bst",
      title: "Lowest Common Ancestor of a BST",
      description: "Given a BST (as array) and two node values `p` and `q`, find their lowest common ancestor.\n\n**Example:**\n```\nInput: root = [6,2,8,0,4,7,9,null,null,3,5], p = 2, q = 8\nOutput: 6\n```",
      difficulty: "medium",
      category: "trees",
      starterCode: "def lowest_common_ancestor(root, p, q):\n    pass\n\nimport json\nroot = json.loads(input())\np = int(input())\nq = int(input())\nprint(lowest_common_ancestor(root, p, q))",
      testCases: JSON.stringify([
        { input: "[6,2,8,0,4,7,9,null,null,3,5]\n2\n8", expected: "6" },
        { input: "[6,2,8,0,4,7,9,null,null,3,5]\n2\n4", expected: "2" },
      ]),
      solutionApproach: "Use BST property: if both < node go left; if both > go right; else found. O(h).",
      companyTags: JSON.stringify(["Amazon", "Meta", "Google"]),
    },
    {
      slug: "binary-tree-right-side-view",
      title: "Binary Tree Right Side View",
      description: "Given a binary tree (as array), return the values of nodes visible from the right side, from top to bottom.\n\n**Example:**\n```\nInput: root = [1,2,3,null,5,null,4]\nOutput: [1,3,4]\n```",
      difficulty: "medium",
      category: "trees",
      starterCode: "def right_side_view(root):\n    pass\n\nimport json\nroot = json.loads(input())\nprint(json.dumps(right_side_view(root)))",
      testCases: JSON.stringify([
        { input: "[1,2,3,null,5,null,4]", expected: "[1, 3, 4]" },
        { input: "[1,null,3]", expected: "[1, 3]" },
        { input: "[]", expected: "[]" },
      ]),
      solutionApproach: "BFS level order, take last node of each level. Or DFS right-first. O(n).",
      companyTags: JSON.stringify(["Amazon", "Meta", "Google"]),
    },
    {
      slug: "diameter-of-binary-tree",
      title: "Diameter of Binary Tree",
      description: "Given a binary tree (as array), find the length of the longest path between any two nodes (diameter). The path doesn't need to pass through root.\n\n**Example:**\n```\nInput: root = [1,2,3,4,5]\nOutput: 3 (path 4→2→1→3 or 5→2→1→3)\n```",
      difficulty: "easy",
      category: "trees",
      starterCode: "def diameter_of_binary_tree(root):\n    pass\n\nimport json\nroot = json.loads(input())\nprint(diameter_of_binary_tree(root))",
      testCases: JSON.stringify([
        { input: "[1,2,3,4,5]", expected: "3" },
        { input: "[1,2]", expected: "1" },
      ]),
      solutionApproach: "At each node, diameter through it = left_depth + right_depth. Track global max. O(n).",
      companyTags: JSON.stringify(["Amazon", "Google", "Meta"]),
    },
    {
      slug: "kth-smallest-bst",
      title: "Kth Smallest Element in a BST",
      description: "Given a BST (as array) and `k`, return the kth smallest element.\n\n**Example:**\n```\nInput: root = [3,1,4,null,2], k = 1\nOutput: 1\n```",
      difficulty: "medium",
      category: "trees",
      starterCode: "def kth_smallest(root, k):\n    pass\n\nimport json\nroot = json.loads(input())\nk = int(input())\nprint(kth_smallest(root, k))",
      testCases: JSON.stringify([
        { input: "[3,1,4,null,2]\n1", expected: "1" },
        { input: "[5,3,6,2,4,null,null,1]\n3", expected: "3" },
      ]),
      solutionApproach: "In-order traversal (gives sorted order). Return kth element. O(H + k).",
      companyTags: JSON.stringify(["Amazon", "Meta", "Google"]),
    },
    {
      slug: "construct-tree-preorder-inorder",
      title: "Construct Tree from Preorder and Inorder",
      description: "Given preorder and inorder traversals, construct the binary tree.\n\n**Example:**\n```\nInput: preorder = [3,9,20,15,7], inorder = [9,3,15,20,7]\nOutput: [3,9,20,null,null,15,7]\n```",
      difficulty: "medium",
      category: "trees",
      starterCode: "def build_tree(preorder, inorder):\n    pass\n\nimport json\npreorder = json.loads(input())\ninorder = json.loads(input())\nprint(json.dumps(build_tree(preorder, inorder)))",
      testCases: JSON.stringify([
        { input: "[3,9,20,15,7]\n[9,3,15,20,7]", expected: "[3, 9, 20, null, null, 15, 7]" },
        { input: "[-1]\n[-1]", expected: "[-1]" },
      ]),
      solutionApproach: "Root = first of preorder. Split inorder at root. Recursively build left/right. O(n) with hash map.",
      companyTags: JSON.stringify(["Amazon", "Google", "Microsoft"]),
    },
    {
      slug: "balanced-binary-tree",
      title: "Balanced Binary Tree",
      description: "Given a binary tree (as array), determine if it is height-balanced (depths of subtrees differ by at most 1).\n\n**Example:**\n```\nInput: root = [3,9,20,null,null,15,7]\nOutput: True\n```",
      difficulty: "easy",
      category: "trees",
      starterCode: "def is_balanced(root):\n    pass\n\nimport json\nroot = json.loads(input())\nprint(is_balanced(root))",
      testCases: JSON.stringify([
        { input: "[3,9,20,null,null,15,7]", expected: "True" },
        { input: "[1,2,2,3,3,null,null,4,4]", expected: "False" },
      ]),
      solutionApproach: "Recursive height check. If any subtree is unbalanced, return -1 to propagate. O(n).",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },

    // ═══════════════════════════════════════════════════════
    // BINARY SEARCH — 4 new problems
    // ═══════════════════════════════════════════════════════
    {
      slug: "first-bad-version",
      title: "First Bad Version",
      description: "You have `n` versions `[1, 2, ..., n]`. Find the first bad one given `isBadVersion(version)` API.\n\nFor simplicity: given array where index=0 means good, index=1 means bad.\n\n**Example:**\n```\nInput: n = 5, bad = 4\nOutput: 4\n```",
      difficulty: "easy",
      category: "binary-search",
      starterCode: "def first_bad_version(n, bad):\n    def is_bad(v):\n        return v >= bad\n    lo, hi = 1, n\n    while lo < hi:\n        mid = (lo + hi) // 2\n        if is_bad(mid):\n            hi = mid\n        else:\n            lo = mid + 1\n    return lo\n\nn = int(input())\nbad = int(input())\nprint(first_bad_version(n, bad))",
      testCases: JSON.stringify([
        { input: "5\n4", expected: "4" },
        { input: "1\n1", expected: "1" },
      ]),
      solutionApproach: "Binary search: if mid is bad, search left including mid. Else search right. O(log n).",
      companyTags: JSON.stringify(["Meta", "Amazon", "Google"]),
    },
    {
      slug: "find-peak-element",
      title: "Find Peak Element",
      description: "Given an array where adjacent elements are never equal, find a peak element (greater than neighbors). Return its index.\n\n**Example:**\n```\nInput: nums = [1,2,3,1]\nOutput: 2\n```\n\nMust be O(log n).",
      difficulty: "medium",
      category: "binary-search",
      starterCode: "def find_peak(nums):\n    pass\n\nimport json\nnums = json.loads(input())\nprint(find_peak(nums))",
      testCases: JSON.stringify([
        { input: "[1,2,3,1]", expected: "2" },
        { input: "[1,2,1,3,5,6,4]", expected: "5" },
      ]),
      solutionApproach: "Binary search: if nums[mid] < nums[mid+1], peak is on right. Else peak is on left or at mid. O(log n).",
      companyTags: JSON.stringify(["Meta", "Google", "Amazon"]),
    },
    {
      slug: "search-2d-matrix",
      title: "Search a 2D Matrix",
      description: "Given an `m x n` matrix (each row sorted, first of next row > last of prev), search for a target.\n\n**Example:**\n```\nInput: matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 3\nOutput: True\n```",
      difficulty: "medium",
      category: "binary-search",
      starterCode: "def search_matrix(matrix, target):\n    pass\n\nimport json\nmatrix = json.loads(input())\ntarget = int(input())\nprint(search_matrix(matrix, target))",
      testCases: JSON.stringify([
        { input: "[[1,3,5,7],[10,11,16,20],[23,30,34,60]]\n3", expected: "True" },
        { input: "[[1,3,5,7],[10,11,16,20],[23,30,34,60]]\n13", expected: "False" },
      ]),
      solutionApproach: "Treat as flattened sorted array. Binary search with row=mid//cols, col=mid%cols. O(log(m*n)).",
      companyTags: JSON.stringify(["Amazon", "Google", "Microsoft"]),
    },
    {
      slug: "koko-eating-bananas",
      title: "Koko Eating Bananas",
      description: "Koko can eat at speed `k` bananas/hour. Given piles and `h` hours, find minimum `k` to eat all bananas in time.\n\n**Example:**\n```\nInput: piles = [3,6,7,11], h = 8\nOutput: 4\n```",
      difficulty: "medium",
      category: "binary-search",
      starterCode: "import math\ndef min_eating_speed(piles, h):\n    pass\n\nimport json\npiles = json.loads(input())\nh = int(input())\nprint(min_eating_speed(piles, h))",
      testCases: JSON.stringify([
        { input: "[3,6,7,11]\n8", expected: "4" },
        { input: "[30,11,23,4,20]\n5", expected: "30" },
        { input: "[30,11,23,4,20]\n6", expected: "23" },
      ]),
      solutionApproach: "Binary search on k (1 to max(piles)). Check if sum(ceil(pile/k)) <= h. O(n log max).",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },

    // ═══════════════════════════════════════════════════════
    // TWO POINTERS — 4 new problems
    // ═══════════════════════════════════════════════════════
    {
      slug: "remove-duplicates-sorted",
      title: "Remove Duplicates from Sorted Array",
      description: "Given a sorted array `nums`, remove duplicates in-place. Return the new length.\n\n**Example:**\n```\nInput: nums = [1,1,2]\nOutput: 2, nums = [1,2,...]\n```",
      difficulty: "easy",
      category: "two-pointers",
      starterCode: "def remove_duplicates(nums):\n    pass\n\nimport json\nnums = json.loads(input())\nk = remove_duplicates(nums)\nprint(json.dumps(nums[:k]))",
      testCases: JSON.stringify([
        { input: "[1,1,2]", expected: "[1, 2]" },
        { input: "[0,0,1,1,1,2,2,3,3,4]", expected: "[0, 1, 2, 3, 4]" },
      ]),
      solutionApproach: "Slow pointer tracks insertion. Fast pointer scans. When different, copy to slow+1. O(n).",
      companyTags: JSON.stringify(["Amazon", "Meta", "Google"]),
    },
    {
      slug: "four-sum",
      title: "4Sum",
      description: "Given array `nums` and target, return all unique quadruplets that sum to target.\n\n**Example:**\n```\nInput: nums = [1,0,-1,0,-2,2], target = 0\nOutput: [[-2,-1,1,2],[-2,0,0,2],[-1,0,0,1]]\n```",
      difficulty: "medium",
      category: "two-pointers",
      starterCode: "def four_sum(nums, target):\n    pass\n\nimport json\nnums = json.loads(input())\ntarget = int(input())\nresult = four_sum(nums, target)\nprint(json.dumps(sorted([sorted(x) for x in result])))",
      testCases: JSON.stringify([
        { input: "[1,0,-1,0,-2,2]\n0", expected: "[[-2, -1, 1, 2], [-2, 0, 0, 2], [-1, 0, 0, 1]]" },
        { input: "[2,2,2,2,2]\n8", expected: "[[2, 2, 2, 2]]" },
      ]),
      solutionApproach: "Sort + two nested loops + two pointers. Skip duplicates. O(n³).",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },
    {
      slug: "valid-palindrome-ii",
      title: "Valid Palindrome II",
      description: "Given a string `s`, return `True` if it can become a palindrome after deleting at most one character.\n\n**Example:**\n```\nInput: s = \"abca\"\nOutput: True (delete 'c' or 'b')\n```",
      difficulty: "easy",
      category: "two-pointers",
      starterCode: "def valid_palindrome(s):\n    pass\n\ns = input().strip()\nprint(valid_palindrome(s))",
      testCases: JSON.stringify([
        { input: "aba", expected: "True" },
        { input: "abca", expected: "True" },
        { input: "abc", expected: "False" },
      ]),
      solutionApproach: "Two pointers from both ends. On mismatch, try skipping left OR right and check if remainder is palindrome. O(n).",
      companyTags: JSON.stringify(["Meta", "Amazon"]),
    },
    {
      slug: "boats-to-save-people",
      title: "Boats to Save People",
      description: "Given people's weights and a boat limit (each boat carries at most 2 people), find minimum boats needed.\n\n**Example:**\n```\nInput: people = [3,2,2,1], limit = 3\nOutput: 3\n```",
      difficulty: "medium",
      category: "two-pointers",
      starterCode: "def num_rescue_boats(people, limit):\n    pass\n\nimport json\npeople = json.loads(input())\nlimit = int(input())\nprint(num_rescue_boats(people, limit))",
      testCases: JSON.stringify([
        { input: "[1,2]\n3", expected: "1" },
        { input: "[3,2,2,1]\n3", expected: "3" },
        { input: "[3,5,3,4]\n5", expected: "4" },
      ]),
      solutionApproach: "Sort. Two pointers from lightest and heaviest. If pair fits, both go. Else heaviest alone. O(n log n).",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },

    // ═══════════════════════════════════════════════════════
    // SLIDING WINDOW — 4 new problems
    // ═══════════════════════════════════════════════════════
    {
      slug: "max-sliding-window",
      title: "Sliding Window Maximum",
      description: "Given array `nums` and window size `k`, return the max value in each sliding window.\n\n**Example:**\n```\nInput: nums = [1,3,-1,-3,5,3,6,7], k = 3\nOutput: [3,3,5,5,6,7]\n```",
      difficulty: "hard",
      category: "sliding-window",
      starterCode: "def max_sliding_window(nums, k):\n    pass\n\nimport json\nnums = json.loads(input())\nk = int(input())\nprint(json.dumps(max_sliding_window(nums, k)))",
      testCases: JSON.stringify([
        { input: "[1,3,-1,-3,5,3,6,7]\n3", expected: "[3, 3, 5, 5, 6, 7]" },
        { input: "[1]\n1", expected: "[1]" },
      ]),
      solutionApproach: "Monotonic decreasing deque. Remove smaller elements from back before adding. O(n).",
      companyTags: JSON.stringify(["Amazon", "Google", "Microsoft"]),
    },
    {
      slug: "permutation-in-string",
      title: "Permutation in String",
      description: "Given two strings `s1` and `s2`, return `True` if `s2` contains a permutation of `s1`.\n\n**Example:**\n```\nInput: s1 = \"ab\", s2 = \"eidbaooo\"\nOutput: True (\"ba\" is a permutation of \"ab\")\n```",
      difficulty: "medium",
      category: "sliding-window",
      starterCode: "def check_inclusion(s1, s2):\n    pass\n\ns1 = input().strip()\ns2 = input().strip()\nprint(check_inclusion(s1, s2))",
      testCases: JSON.stringify([
        { input: "ab\neidbaooo", expected: "True" },
        { input: "ab\neidboaoo", expected: "False" },
      ]),
      solutionApproach: "Fixed-size sliding window of len(s1). Compare character counts. O(n).",
      companyTags: JSON.stringify(["Amazon", "Microsoft"]),
    },
    {
      slug: "longest-repeating-character-replacement",
      title: "Longest Repeating Character Replacement",
      description: "Given string `s` and integer `k`, you can change at most `k` characters. Find the length of the longest substring with all the same characters.\n\n**Example:**\n```\nInput: s = \"AABABBA\", k = 1\nOutput: 4 (replace one B in \"AABA\")\n```",
      difficulty: "medium",
      category: "sliding-window",
      starterCode: "def character_replacement(s, k):\n    pass\n\ns = input().strip()\nk = int(input())\nprint(character_replacement(s, k))",
      testCases: JSON.stringify([
        { input: "ABAB\n2", expected: "4" },
        { input: "AABABBA\n1", expected: "4" },
      ]),
      solutionApproach: "Sliding window. Track max frequency in window. If window_size - max_freq > k, shrink. O(n).",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },
    {
      slug: "fruit-into-baskets",
      title: "Fruit Into Baskets",
      description: "Given an array of fruit types, find the longest subarray with at most 2 distinct types.\n\n**Example:**\n```\nInput: fruits = [1,2,1,2,3]\nOutput: 4 ([1,2,1,2])\n```",
      difficulty: "medium",
      category: "sliding-window",
      starterCode: "def total_fruit(fruits):\n    pass\n\nimport json\nfruits = json.loads(input())\nprint(total_fruit(fruits))",
      testCases: JSON.stringify([
        { input: "[1,2,1]", expected: "3" },
        { input: "[0,1,2,2]", expected: "3" },
        { input: "[1,2,3,2,2]", expected: "4" },
      ]),
      solutionApproach: "Sliding window with hash map tracking counts. Shrink when > 2 types. O(n).",
      companyTags: JSON.stringify(["Google", "Amazon"]),
    },

    // ═══════════════════════════════════════════════════════
    // BACKTRACKING — 4 new problems
    // ═══════════════════════════════════════════════════════
    {
      slug: "combination-sum",
      title: "Combination Sum",
      description: "Given candidates (no duplicates) and a target, find all unique combinations that sum to target. Numbers can be used unlimited times.\n\n**Example:**\n```\nInput: candidates = [2,3,6,7], target = 7\nOutput: [[2,2,3],[7]]\n```",
      difficulty: "medium",
      category: "backtracking",
      starterCode: "def combination_sum(candidates, target):\n    pass\n\nimport json\ncandidates = json.loads(input())\ntarget = int(input())\nresult = combination_sum(candidates, target)\nprint(json.dumps(sorted([sorted(x) for x in result])))",
      testCases: JSON.stringify([
        { input: "[2,3,6,7]\n7", expected: "[[2, 2, 3], [7]]" },
        { input: "[2,3,5]\n8", expected: "[[2, 2, 2, 2], [2, 3, 3], [3, 5]]" },
      ]),
      solutionApproach: "Backtracking: for each candidate, include it (reuse allowed) or skip. Prune if sum > target. O(n^(T/M)).",
      companyTags: JSON.stringify(["Amazon", "Meta", "Google"]),
    },
    {
      slug: "combination-sum-ii",
      title: "Combination Sum II",
      description: "Given candidates (may have duplicates) and a target, find unique combinations that sum to target. Each number can only be used once.\n\n**Example:**\n```\nInput: candidates = [10,1,2,7,6,1,5], target = 8\nOutput: [[1,1,6],[1,2,5],[1,7],[2,6]]\n```",
      difficulty: "medium",
      category: "backtracking",
      starterCode: "def combination_sum_2(candidates, target):\n    pass\n\nimport json\ncandidates = json.loads(input())\ntarget = int(input())\nresult = combination_sum_2(candidates, target)\nprint(json.dumps(sorted([sorted(x) for x in result])))",
      testCases: JSON.stringify([
        { input: "[10,1,2,7,6,1,5]\n8", expected: "[[1, 1, 6], [1, 2, 5], [1, 7], [2, 6]]" },
        { input: "[2,5,2,1,2]\n5", expected: "[[1, 2, 2], [5]]" },
      ]),
      solutionApproach: "Sort, backtrack with index. Skip consecutive duplicates at same level. O(2^n).",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },
    {
      slug: "n-queens",
      title: "N-Queens",
      description: "Place `n` queens on an `n x n` chessboard so that no two queens attack each other. Return the number of solutions.\n\n**Example:**\n```\nInput: n = 4\nOutput: 2\n```",
      difficulty: "hard",
      category: "backtracking",
      starterCode: "def total_n_queens(n):\n    pass\n\nn = int(input())\nprint(total_n_queens(n))",
      testCases: JSON.stringify([
        { input: "4", expected: "2" },
        { input: "1", expected: "1" },
        { input: "8", expected: "92" },
      ]),
      solutionApproach: "Backtracking row by row. Track used columns and diagonals with sets. O(n!).",
      companyTags: JSON.stringify(["Amazon", "Google", "Microsoft"]),
    },
    {
      slug: "palindrome-partitioning",
      title: "Palindrome Partitioning",
      description: "Given a string `s`, partition it such that every substring is a palindrome. Return all possible partitions.\n\n**Example:**\n```\nInput: s = \"aab\"\nOutput: [[\"a\",\"a\",\"b\"],[\"aa\",\"b\"]]\n```",
      difficulty: "medium",
      category: "backtracking",
      starterCode: "def partition(s):\n    pass\n\nimport json\ns = input().strip()\nresult = partition(s)\nprint(json.dumps(sorted(result)))",
      testCases: JSON.stringify([
        { input: "aab", expected: '[["a", "a", "b"], ["aa", "b"]]' },
        { input: "a", expected: '[["a"]]' },
      ]),
      solutionApproach: "Backtracking: at each position, try all substrings that are palindromes. O(n * 2^n).",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },

    // ═══════════════════════════════════════════════════════
    // INTERVALS — 3 new problems
    // ═══════════════════════════════════════════════════════
    {
      slug: "insert-interval",
      title: "Insert Interval",
      description: "Insert a new interval into a non-overlapping sorted interval list, merging if necessary.\n\n**Example:**\n```\nInput: intervals = [[1,3],[6,9]], newInterval = [2,5]\nOutput: [[1,5],[6,9]]\n```",
      difficulty: "medium",
      category: "intervals",
      starterCode: "def insert(intervals, new_interval):\n    pass\n\nimport json\nintervals = json.loads(input())\nnew_interval = json.loads(input())\nprint(json.dumps(insert(intervals, new_interval)))",
      testCases: JSON.stringify([
        { input: "[[1,3],[6,9]]\n[2,5]", expected: "[[1, 5], [6, 9]]" },
        { input: "[[1,2],[3,5],[6,7],[8,10],[12,16]]\n[4,8]", expected: "[[1, 2], [3, 10], [12, 16]]" },
      ]),
      solutionApproach: "Three phases: add intervals before, merge overlapping, add intervals after. O(n).",
      companyTags: JSON.stringify(["Amazon", "Google", "Meta"]),
    },
    {
      slug: "non-overlapping-intervals",
      title: "Non-overlapping Intervals",
      description: "Given intervals, return the minimum number of intervals to remove to make the rest non-overlapping.\n\n**Example:**\n```\nInput: intervals = [[1,2],[2,3],[3,4],[1,3]]\nOutput: 1 (remove [1,3])\n```",
      difficulty: "medium",
      category: "intervals",
      starterCode: "def erase_overlap(intervals):\n    pass\n\nimport json\nintervals = json.loads(input())\nprint(erase_overlap(intervals))",
      testCases: JSON.stringify([
        { input: "[[1,2],[2,3],[3,4],[1,3]]", expected: "1" },
        { input: "[[1,2],[1,2],[1,2]]", expected: "2" },
        { input: "[[1,2],[2,3]]", expected: "0" },
      ]),
      solutionApproach: "Sort by end time. Greedily keep intervals that don't overlap. Count removed. O(n log n).",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },
    {
      slug: "meeting-rooms-ii",
      title: "Meeting Rooms II",
      description: "Given meeting intervals, find the minimum number of conference rooms required.\n\n**Example:**\n```\nInput: intervals = [[0,30],[5,10],[15,20]]\nOutput: 2\n```",
      difficulty: "medium",
      category: "intervals",
      starterCode: "def min_meeting_rooms(intervals):\n    pass\n\nimport json\nintervals = json.loads(input())\nprint(min_meeting_rooms(intervals))",
      testCases: JSON.stringify([
        { input: "[[0,30],[5,10],[15,20]]", expected: "2" },
        { input: "[[7,10],[2,4]]", expected: "1" },
      ]),
      solutionApproach: "Sort starts and ends separately. Two pointers: if start < end, need room, else free room. Or min-heap. O(n log n).",
      companyTags: JSON.stringify(["Amazon", "Google", "Meta", "Microsoft"]),
    },

    // ═══════════════════════════════════════════════════════
    // HEAPS — 5 new problems
    // ═══════════════════════════════════════════════════════
    {
      slug: "last-stone-weight",
      title: "Last Stone Weight",
      description: "Given stones with weights, smash the two heaviest. If equal, both destroyed. If not, lighter is destroyed, heavier becomes `y - x`. Return last stone weight (or 0).\n\n**Example:**\n```\nInput: stones = [2,7,4,1,8,1]\nOutput: 1\n```",
      difficulty: "easy",
      category: "heaps",
      starterCode: "def last_stone_weight(stones):\n    pass\n\nimport json\nstones = json.loads(input())\nprint(last_stone_weight(stones))",
      testCases: JSON.stringify([
        { input: "[2,7,4,1,8,1]", expected: "1" },
        { input: "[1]", expected: "1" },
      ]),
      solutionApproach: "Max-heap. Pop two largest, push difference if non-zero. Repeat. O(n log n).",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },
    {
      slug: "k-closest-points-to-origin",
      title: "K Closest Points to Origin",
      description: "Given an array of points on the XY plane, return the `k` closest to the origin.\n\n**Example:**\n```\nInput: points = [[1,3],[-2,2]], k = 1\nOutput: [[-2,2]]\n```",
      difficulty: "medium",
      category: "heaps",
      starterCode: "def k_closest(points, k):\n    pass\n\nimport json\npoints = json.loads(input())\nk = int(input())\nresult = k_closest(points, k)\nprint(json.dumps(sorted(result)))",
      testCases: JSON.stringify([
        { input: "[[1,3],[-2,2]]\n1", expected: "[[-2, 2]]" },
        { input: "[[3,3],[5,-1],[-2,4]]\n2", expected: "[[-2, 4], [3, 3]]" },
      ]),
      solutionApproach: "Min-heap by distance, pop k times. Or max-heap of size k. Or quickselect. O(n log k).",
      companyTags: JSON.stringify(["Amazon", "Meta", "Google"]),
    },
    {
      slug: "task-scheduler",
      title: "Task Scheduler",
      description: "Given tasks and a cooldown period `n`, find the minimum time to finish all tasks. Same task needs `n` intervals between executions.\n\n**Example:**\n```\nInput: tasks = [\"A\",\"A\",\"A\",\"B\",\"B\",\"B\"], n = 2\nOutput: 8 (A B idle A B idle A B)\n```",
      difficulty: "medium",
      category: "heaps",
      starterCode: "def least_interval(tasks, n):\n    pass\n\nimport json\ntasks = json.loads(input())\nn = int(input())\nprint(least_interval(tasks, n))",
      testCases: JSON.stringify([
        { input: '["A","A","A","B","B","B"]\n2', expected: "8" },
        { input: '["A","A","A","B","B","B"]\n0', expected: "6" },
        { input: '["A","A","A","A","A","A","B","C","D","E","F","G"]\n2', expected: "16" },
      ]),
      solutionApproach: "Greedy or heap: most frequent task determines frame. Formula: (maxFreq-1)*(n+1) + numMax. O(n).",
      companyTags: JSON.stringify(["Meta", "Amazon", "Google", "Microsoft"]),
    },
    {
      slug: "find-median-from-data-stream",
      title: "Find Median from Data Stream",
      description: "Design a class to add numbers from a data stream and return the median efficiently.\n\n**Example:**\n```\nadd(1), add(2), median() → 1.5\nadd(3), median() → 2.0\n```",
      difficulty: "hard",
      category: "heaps",
      starterCode: "import heapq\nclass MedianFinder:\n    def __init__(self):\n        pass\n    def add_num(self, num):\n        pass\n    def find_median(self):\n        pass\n\nimport json\nops = json.loads(input())\nargs = json.loads(input())\nmf = MedianFinder()\nresults = [None]\nfor i in range(1, len(ops)):\n    if ops[i] == 'addNum':\n        mf.add_num(args[i][0])\n        results.append(None)\n    elif ops[i] == 'findMedian':\n        results.append(mf.find_median())\nprint(json.dumps(results))",
      testCases: JSON.stringify([
        { input: '["MedianFinder","addNum","addNum","findMedian","addNum","findMedian"]\n[[],[1],[2],[],[3],[]]', expected: "[null, null, null, 1.5, null, 2.0]" },
      ]),
      solutionApproach: "Two heaps: max-heap for lower half, min-heap for upper half. Balance sizes. O(log n) add, O(1) median.",
      companyTags: JSON.stringify(["Amazon", "Google", "Microsoft"]),
    },
    {
      slug: "reorganize-string",
      title: "Reorganize String",
      description: "Given a string `s`, rearrange so no two adjacent characters are the same. Return empty string if not possible.\n\n**Example:**\n```\nInput: s = \"aab\"\nOutput: \"aba\"\n```",
      difficulty: "medium",
      category: "heaps",
      starterCode: "def reorganize_string(s):\n    pass\n\ns = input().strip()\nresult = reorganize_string(s)\nprint(result)",
      testCases: JSON.stringify([
        { input: "aab", expected: "aba" },
        { input: "aaab", expected: "" },
      ]),
      solutionApproach: "Max-heap by frequency. Pop two most frequent, place alternately. O(n log k).",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },

    // ═══════════════════════════════════════════════════════
    // GREEDY — 5 new problems
    // ═══════════════════════════════════════════════════════
    {
      slug: "jump-game",
      title: "Jump Game",
      description: "Given an array where `nums[i]` is max jump length from position `i`, determine if you can reach the last index.\n\n**Example:**\n```\nInput: nums = [2,3,1,1,4]\nOutput: True\n```",
      difficulty: "medium",
      category: "greedy",
      starterCode: "def can_jump(nums):\n    pass\n\nimport json\nnums = json.loads(input())\nprint(can_jump(nums))",
      testCases: JSON.stringify([
        { input: "[2,3,1,1,4]", expected: "True" },
        { input: "[3,2,1,0,4]", expected: "False" },
      ]),
      solutionApproach: "Track farthest reachable index. If current > farthest, can't proceed. O(n).",
      companyTags: JSON.stringify(["Amazon", "Google", "Microsoft"]),
    },
    {
      slug: "jump-game-ii",
      title: "Jump Game II",
      description: "Given same setup as Jump Game, return minimum number of jumps to reach the last index.\n\n**Example:**\n```\nInput: nums = [2,3,1,1,4]\nOutput: 2 (jump 1→2, jump 2→5)\n```",
      difficulty: "medium",
      category: "greedy",
      starterCode: "def jump(nums):\n    pass\n\nimport json\nnums = json.loads(input())\nprint(jump(nums))",
      testCases: JSON.stringify([
        { input: "[2,3,1,1,4]", expected: "2" },
        { input: "[2,3,0,1,4]", expected: "2" },
      ]),
      solutionApproach: "BFS-like: track current range end and farthest reachable. Increment jumps at range end. O(n).",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },
    {
      slug: "gas-station",
      title: "Gas Station",
      description: "There are `n` gas stations in a circle. `gas[i]` is fuel, `cost[i]` is cost to next station. Find starting station index to complete the circuit. Return -1 if impossible.\n\n**Example:**\n```\nInput: gas = [1,2,3,4,5], cost = [3,4,5,1,2]\nOutput: 3\n```",
      difficulty: "medium",
      category: "greedy",
      starterCode: "def can_complete_circuit(gas, cost):\n    pass\n\nimport json\ngas = json.loads(input())\ncost = json.loads(input())\nprint(can_complete_circuit(gas, cost))",
      testCases: JSON.stringify([
        { input: "[1,2,3,4,5]\n[3,4,5,1,2]", expected: "3" },
        { input: "[2,3,4]\n[3,4,3]", expected: "-1" },
      ]),
      solutionApproach: "If total gas >= total cost, solution exists. Track current tank; if negative, start from next station. O(n).",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },
    {
      slug: "hand-of-straights",
      title: "Hand of Straights",
      description: "Given an array of cards and group size `W`, can you rearrange them into groups of `W` consecutive numbers?\n\n**Example:**\n```\nInput: hand = [1,2,3,6,2,3,4,7,8], W = 3\nOutput: True ([1,2,3],[2,3,4],[6,7,8])\n```",
      difficulty: "medium",
      category: "greedy",
      starterCode: "def is_n_straight_hand(hand, w):\n    pass\n\nimport json\nhand = json.loads(input())\nw = int(input())\nprint(is_n_straight_hand(hand, w))",
      testCases: JSON.stringify([
        { input: "[1,2,3,6,2,3,4,7,8]\n3", expected: "True" },
        { input: "[1,2,3,4,5]\n4", expected: "False" },
      ]),
      solutionApproach: "Sort + counter. For each remaining minimum, try to form a group of W consecutive. O(n log n).",
      companyTags: JSON.stringify(["Google", "Amazon"]),
    },
    {
      slug: "partition-labels",
      title: "Partition Labels",
      description: "Given a string, partition it so each letter appears in at most one part. Return the sizes of the parts.\n\n**Example:**\n```\nInput: s = \"ababcbacadefegdehijhklij\"\nOutput: [9,7,8]\n```",
      difficulty: "medium",
      category: "greedy",
      starterCode: "def partition_labels(s):\n    pass\n\nimport json\ns = input().strip()\nprint(json.dumps(partition_labels(s)))",
      testCases: JSON.stringify([
        { input: "ababcbacadefegdehijhklij", expected: "[9, 7, 8]" },
        { input: "eccbbbbdec", expected: "[10]" },
      ]),
      solutionApproach: "Record last occurrence of each character. Expand partition to include all characters' last positions. O(n).",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },

    // ═══════════════════════════════════════════════════════
    // MATH & BIT MANIPULATION — 5 new problems
    // ═══════════════════════════════════════════════════════
    {
      slug: "reverse-integer",
      title: "Reverse Integer",
      description: "Given a signed 32-bit integer, return it with its digits reversed. If overflows, return 0.\n\n**Example:**\n```\nInput: x = 123\nOutput: 321\n```\n```\nInput: x = -123\nOutput: -321\n```",
      difficulty: "medium",
      category: "math",
      starterCode: "def reverse(x):\n    pass\n\nx = int(input())\nprint(reverse(x))",
      testCases: JSON.stringify([
        { input: "123", expected: "321" },
        { input: "-123", expected: "-321" },
        { input: "120", expected: "21" },
      ]),
      solutionApproach: "Pop digits with % 10, push to result with * 10. Check overflow before final operation. O(log x).",
      companyTags: JSON.stringify(["Amazon", "Google", "Apple"]),
    },
    {
      slug: "power-of-two",
      title: "Power of Two",
      description: "Given an integer `n`, return `True` if it is a power of two.\n\n**Example:**\n```\nInput: n = 16\nOutput: True\n```",
      difficulty: "easy",
      category: "math",
      starterCode: "def is_power_of_two(n):\n    pass\n\nn = int(input())\nprint(is_power_of_two(n))",
      testCases: JSON.stringify([
        { input: "1", expected: "True" },
        { input: "16", expected: "True" },
        { input: "3", expected: "False" },
      ]),
      solutionApproach: "Bit trick: n > 0 and n & (n-1) == 0. Powers of two have exactly one bit set. O(1).",
      companyTags: JSON.stringify(["Amazon", "Apple"]),
    },
    {
      slug: "counting-bits",
      title: "Counting Bits",
      description: "Given `n`, return an array `ans` of length `n+1` where `ans[i]` is the number of 1-bits in `i`.\n\n**Example:**\n```\nInput: n = 5\nOutput: [0,1,1,2,1,2]\n```",
      difficulty: "easy",
      category: "math",
      starterCode: "def count_bits(n):\n    pass\n\nimport json\nn = int(input())\nprint(json.dumps(count_bits(n)))",
      testCases: JSON.stringify([
        { input: "2", expected: "[0, 1, 1]" },
        { input: "5", expected: "[0, 1, 1, 2, 1, 2]" },
      ]),
      solutionApproach: "DP: ans[i] = ans[i >> 1] + (i & 1). Or ans[i] = ans[i & (i-1)] + 1. O(n).",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },
    {
      slug: "missing-number",
      title: "Missing Number",
      description: "Given array containing `n` distinct numbers from `[0, n]`, find the one missing.\n\n**Example:**\n```\nInput: nums = [3,0,1]\nOutput: 2\n```",
      difficulty: "easy",
      category: "math",
      starterCode: "def missing_number(nums):\n    pass\n\nimport json\nnums = json.loads(input())\nprint(missing_number(nums))",
      testCases: JSON.stringify([
        { input: "[3,0,1]", expected: "2" },
        { input: "[0,1]", expected: "2" },
        { input: "[9,6,4,2,3,5,7,0,1]", expected: "8" },
      ]),
      solutionApproach: "Sum formula: n*(n+1)/2 - sum(nums). Or XOR all numbers with indices. O(n) time, O(1) space.",
      companyTags: JSON.stringify(["Amazon", "Microsoft", "Google"]),
    },
    {
      slug: "number-of-1-bits",
      title: "Number of 1 Bits (Hamming Weight)",
      description: "Given a positive integer, return the number of set bits (1s) in its binary representation.\n\n**Example:**\n```\nInput: n = 11 (binary: 1011)\nOutput: 3\n```",
      difficulty: "easy",
      category: "math",
      starterCode: "def hamming_weight(n):\n    pass\n\nn = int(input())\nprint(hamming_weight(n))",
      testCases: JSON.stringify([
        { input: "11", expected: "3" },
        { input: "128", expected: "1" },
        { input: "2147483645", expected: "30" },
      ]),
      solutionApproach: "Count bits: n = n & (n-1) removes lowest set bit. Count iterations. O(number of bits).",
      companyTags: JSON.stringify(["Amazon", "Apple"]),
    },

    // ═══════════════════════════════════════════════════════
    // STACKS — 4 new problems
    // ═══════════════════════════════════════════════════════
    {
      slug: "daily-temperatures",
      title: "Daily Temperatures",
      description: "Given an array of daily temperatures, return an array where `answer[i]` is how many days until a warmer temperature. If no warmer day, put 0.\n\n**Example:**\n```\nInput: temperatures = [73,74,75,71,69,72,76,73]\nOutput: [1,1,4,2,1,1,0,0]\n```",
      difficulty: "medium",
      category: "stacks",
      starterCode: "def daily_temperatures(temperatures):\n    pass\n\nimport json\ntemperatures = json.loads(input())\nprint(json.dumps(daily_temperatures(temperatures)))",
      testCases: JSON.stringify([
        { input: "[73,74,75,71,69,72,76,73]", expected: "[1, 1, 4, 2, 1, 1, 0, 0]" },
        { input: "[30,40,50,60]", expected: "[1, 1, 1, 0]" },
        { input: "[30,60,90]", expected: "[1, 1, 0]" },
      ]),
      solutionApproach: "Monotonic decreasing stack of indices. When a warmer temp appears, pop and calculate days. O(n).",
      companyTags: JSON.stringify(["Amazon", "Google", "Meta"]),
    },
    {
      slug: "evaluate-reverse-polish-notation",
      title: "Evaluate Reverse Polish Notation",
      description: "Evaluate the value of an arithmetic expression in Reverse Polish Notation (postfix).\n\n**Example:**\n```\nInput: tokens = [\"2\",\"1\",\"+\",\"3\",\"*\"]\nOutput: 9 ((2+1)*3)\n```",
      difficulty: "medium",
      category: "stacks",
      starterCode: "def eval_rpn(tokens):\n    pass\n\nimport json\ntokens = json.loads(input())\nprint(eval_rpn(tokens))",
      testCases: JSON.stringify([
        { input: '["2","1","+","3","*"]', expected: "9" },
        { input: '["4","13","5","/","+"]', expected: "6" },
        { input: '["10","6","9","3","+","-11","*","/","*","17","+","5","+"]', expected: "22" },
      ]),
      solutionApproach: "Stack: push numbers, pop two on operator, compute, push result. O(n).",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },
    {
      slug: "largest-rectangle-histogram",
      title: "Largest Rectangle in Histogram",
      description: "Given an array of heights representing a histogram, find the area of the largest rectangle.\n\n**Example:**\n```\nInput: heights = [2,1,5,6,2,3]\nOutput: 10\n```",
      difficulty: "hard",
      category: "stacks",
      starterCode: "def largest_rectangle_area(heights):\n    pass\n\nimport json\nheights = json.loads(input())\nprint(largest_rectangle_area(heights))",
      testCases: JSON.stringify([
        { input: "[2,1,5,6,2,3]", expected: "10" },
        { input: "[2,4]", expected: "4" },
      ]),
      solutionApproach: "Monotonic increasing stack. Pop when shorter bar found, calculate area with width to last smaller. O(n).",
      companyTags: JSON.stringify(["Amazon", "Google", "Microsoft"]),
    },
    {
      slug: "generate-parentheses",
      title: "Generate Parentheses",
      description: "Given `n` pairs of parentheses, generate all valid combinations.\n\n**Example:**\n```\nInput: n = 3\nOutput: [\"((()))\",\"(()())\",\"(())()\",\"()(())\",\"()()()\"]\n```",
      difficulty: "medium",
      category: "stacks",
      starterCode: "def generate_parenthesis(n):\n    pass\n\nimport json\nn = int(input())\nresult = generate_parenthesis(n)\nprint(json.dumps(sorted(result)))",
      testCases: JSON.stringify([
        { input: "3", expected: '["((()))", "(()())", "(())()", "()(())", "()()()"]' },
        { input: "1", expected: '["()"]' },
      ]),
      solutionApproach: "Backtracking with open/close counts. Add '(' if open < n, add ')' if close < open. O(4^n / sqrt(n)).",
      companyTags: JSON.stringify(["Amazon", "Google", "Microsoft"]),
    },

    // ═══════════════════════════════════════════════════════
    // DESIGN — 3 new problems
    // ═══════════════════════════════════════════════════════
    {
      slug: "min-stack-v2",
      title: "Design Min/Max Stack",
      description: "Design a stack that supports push, pop, top, getMin, and getMax all in O(1).\n\n**Example:**\n```\npush(5), push(3), push(7)\ngetMin() → 3, getMax() → 7\npop() → 7, getMax() → 5\n```",
      difficulty: "medium",
      category: "design",
      starterCode: "class MinMaxStack:\n    def __init__(self):\n        pass\n    def push(self, val):\n        pass\n    def pop(self):\n        pass\n    def top(self):\n        pass\n    def get_min(self):\n        pass\n    def get_max(self):\n        pass\n\nstack = MinMaxStack()\nops = input().split(',')\nfor op in ops:\n    op = op.strip()\n    if op.startswith('push'):\n        val = int(op.split('(')[1].rstrip(')'))\n        stack.push(val)\n    elif op == 'pop':\n        print(stack.pop())\n    elif op == 'top':\n        print(stack.top())\n    elif op == 'getmin':\n        print(stack.get_min())\n    elif op == 'getmax':\n        print(stack.get_max())",
      testCases: JSON.stringify([
        { input: "push(5),push(3),push(7),getmin,getmax,pop,getmax", expected: "3\n7\n7\n5" },
      ]),
      solutionApproach: "Store (value, current_min, current_max) tuples on stack. Each push records extremes at that level. O(1) all ops.",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },
    {
      slug: "implement-queue-using-stacks",
      title: "Implement Queue using Stacks",
      description: "Implement a FIFO queue using only two stacks. Support push, pop, peek, and empty.\n\n**Example:**\n```\npush(1), push(2), peek() → 1, pop() → 1, empty() → False\n```",
      difficulty: "easy",
      category: "design",
      starterCode: "class MyQueue:\n    def __init__(self):\n        pass\n    def push(self, x):\n        pass\n    def pop(self):\n        pass\n    def peek(self):\n        pass\n    def empty(self):\n        pass\n\nimport json\nops = json.loads(input())\nargs = json.loads(input())\nqueue = MyQueue()\nresults = [None]\nfor i in range(1, len(ops)):\n    if ops[i] == 'push':\n        queue.push(args[i][0])\n        results.append(None)\n    elif ops[i] == 'pop':\n        results.append(queue.pop())\n    elif ops[i] == 'peek':\n        results.append(queue.peek())\n    elif ops[i] == 'empty':\n        results.append(queue.empty())\nprint(json.dumps(results))",
      testCases: JSON.stringify([
        { input: '["MyQueue","push","push","peek","pop","empty"]\n[[],[1],[2],[],[],[]]', expected: "[null, null, null, 1, 1, false]" },
      ]),
      solutionApproach: "Two stacks: input stack and output stack. On pop/peek, if output empty, pour input→output. Amortized O(1).",
      companyTags: JSON.stringify(["Amazon", "Google", "Microsoft"]),
    },
    {
      slug: "time-based-key-value-store",
      title: "Time Based Key-Value Store",
      description: "Design a time-based key-value data structure. `set(key, value, timestamp)` stores, `get(key, timestamp)` returns value with largest timestamp <= given timestamp.\n\n**Example:**\n```\nset(\"foo\",\"bar\",1), get(\"foo\",1) → \"bar\"\nset(\"foo\",\"bar2\",4), get(\"foo\",4) → \"bar2\"\nget(\"foo\",3) → \"bar\"\n```",
      difficulty: "medium",
      category: "design",
      starterCode: "class TimeMap:\n    def __init__(self):\n        pass\n    def set(self, key, value, timestamp):\n        pass\n    def get(self, key, timestamp):\n        pass\n\nimport json\nops = json.loads(input())\nargs = json.loads(input())\ntm = TimeMap()\nresults = [None]\nfor i in range(1, len(ops)):\n    if ops[i] == 'set':\n        tm.set(args[i][0], args[i][1], args[i][2])\n        results.append(None)\n    elif ops[i] == 'get':\n        results.append(tm.get(args[i][0], args[i][1]))\nprint(json.dumps(results))",
      testCases: JSON.stringify([
        { input: '["TimeMap","set","get","get","set","get","get"]\n[[],["foo","bar",1],["foo",1],["foo",3],["foo","bar2",4],["foo",4],["foo",5]]', expected: '[null, null, "bar", "bar", null, "bar2", "bar2"]' },
      ]),
      solutionApproach: "Hash map of key → list of (timestamp, value). Binary search on get. O(1) set, O(log n) get.",
      companyTags: JSON.stringify(["Google", "Amazon", "Meta"]),
    },

    // ═══════════════════════════════════════════════════════
    // RECURSION — 4 new problems
    // ═══════════════════════════════════════════════════════
    {
      slug: "fibonacci-number",
      title: "Fibonacci Number",
      description: "Given `n`, return the nth Fibonacci number.\n\n`F(0) = 0, F(1) = 1, F(n) = F(n-1) + F(n-2)`\n\n**Example:**\n```\nInput: n = 4\nOutput: 3\n```",
      difficulty: "easy",
      category: "recursion",
      starterCode: "def fib(n):\n    pass\n\nn = int(input())\nprint(fib(n))",
      testCases: JSON.stringify([
        { input: "2", expected: "1" },
        { input: "3", expected: "2" },
        { input: "4", expected: "3" },
      ]),
      solutionApproach: "Iterative or memoized recursion. O(n) time with two variables.",
      companyTags: JSON.stringify(["Amazon", "Google"]),
    },
    {
      slug: "power-function",
      title: "Pow(x, n)",
      description: "Implement `pow(x, n)`, which calculates `x` raised to the power `n`.\n\n**Example:**\n```\nInput: x = 2.0, n = 10\nOutput: 1024.0\n```\n\nHandle negative `n`.",
      difficulty: "medium",
      category: "recursion",
      starterCode: "def my_pow(x, n):\n    pass\n\nx = float(input())\nn = int(input())\nprint(my_pow(x, n))",
      testCases: JSON.stringify([
        { input: "2.0\n10", expected: "1024.0" },
        { input: "2.1\n3", expected: "9.261" },
        { input: "2.0\n-2", expected: "0.25" },
      ]),
      solutionApproach: "Fast exponentiation: x^n = (x^(n/2))^2. Handle negative n with 1/x. O(log n).",
      companyTags: JSON.stringify(["Amazon", "Google", "Meta"]),
    },
    {
      slug: "merge-sort-implementation",
      title: "Merge Sort",
      description: "Implement merge sort to sort an array.\n\n**Example:**\n```\nInput: nums = [5,2,3,1]\nOutput: [1,2,3,5]\n```",
      difficulty: "medium",
      category: "recursion",
      starterCode: "def merge_sort(nums):\n    pass\n\nimport json\nnums = json.loads(input())\nprint(json.dumps(merge_sort(nums)))",
      testCases: JSON.stringify([
        { input: "[5,2,3,1]", expected: "[1, 2, 3, 5]" },
        { input: "[5,1,1,2,0,0]", expected: "[0, 0, 1, 1, 2, 5]" },
      ]),
      solutionApproach: "Divide array in half, recursively sort each, merge sorted halves. O(n log n) time, O(n) space.",
      companyTags: JSON.stringify(["Amazon", "Google", "Microsoft"]),
    },
    {
      slug: "flatten-nested-list",
      title: "Flatten Nested List",
      description: "Given a nested list of integers, flatten it into a single list.\n\n**Example:**\n```\nInput: [[1,1],2,[1,1]]\nOutput: [1,1,2,1,1]\n```",
      difficulty: "medium",
      category: "recursion",
      starterCode: "def flatten(nested_list):\n    pass\n\nimport json\nnested = json.loads(input())\nprint(json.dumps(flatten(nested)))",
      testCases: JSON.stringify([
        { input: "[[1,1],2,[1,1]]", expected: "[1, 1, 2, 1, 1]" },
        { input: "[1,[4,[6]]]", expected: "[1, 4, 6]" },
      ]),
      solutionApproach: "Recursive: if element is list, recurse. If integer, append to result. O(n) where n is total elements.",
      companyTags: JSON.stringify(["Amazon", "Google", "Meta"]),
    },
  ];

  let created = 0;
  let skipped = 0;
  for (const problem of problems) {
    try {
      await prisma.problem.upsert({
        where: { slug: problem.slug },
        update: {},
        create: {
          slug: problem.slug,
          title: problem.title,
          description: problem.description,
          difficulty: problem.difficulty,
          category: problem.category,
          starterCode: problem.starterCode,
          testCases: problem.testCases,
          solutionApproach: problem.solutionApproach,
          companyTags: problem.companyTags,
        },
      });
      created++;
      console.log(`  ✓ ${problem.title} (${problem.difficulty} | ${problem.category})`);
    } catch (e) {
      skipped++;
      console.log(`  ⚠ Skipped ${problem.slug}: ${(e as Error).message?.slice(0, 60)}`);
    }
  }

  console.log(`\n✅ Seeded ${created} new problems (${skipped} skipped)`);
  console.log(`   Total problems in DB: ${await prisma.problem.count()}`);
}

main()
  .catch((e) => { console.error("❌ Seed failed:", e); process.exit(1); })
  .finally(() => prisma.$disconnect());
