import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export async function seedExpansionCards() {
  console.log("🃏 Seeding 100 expansion prediction cards...\n");

  const cards = [
    // ══════════════════════════════════════════════════════════════
    // GREEDY — 10 cards
    // ══════════════════════════════════════════════════════════════
    {
      type: "time-complexity",
      topic: "greedy",
      difficulty: "intermediate",
      question: "What is the time complexity of the Activity Selection problem using a greedy approach?",
      options: JSON.stringify(["O(n)", "O(n log n)", "O(n²)", "O(2ⁿ)"]),
      correctAnswer: "O(n log n)",
      explanation: "Activity selection requires sorting by finish time (O(n log n)), then a single linear scan (O(n)). The bottleneck is sorting.",
      xpReward: 15,
    },
    {
      type: "pattern-match",
      topic: "greedy",
      difficulty: "intermediate",
      question: "You need to find the minimum number of conference rooms for overlapping meetings. Which approach works best?",
      options: JSON.stringify(["Greedy with sorted start/end times", "Dynamic Programming", "Backtracking", "Binary Search"]),
      correctAnswer: "Greedy with sorted start/end times",
      explanation: "Sort start times and end times separately. Use two pointers to track active meetings — a classic sweep-line greedy approach.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "greedy",
      difficulty: "beginner",
      question: "What is the output?\n\ncoins = [1, 5, 10, 25]\ntarget = 30\ncount = 0\nfor c in reversed(coins):\n    count += target // c\n    target %= c\nprint(count)",
      options: JSON.stringify(["2", "3", "6", "30"]),
      correctAnswer: "2",
      explanation: "Greedy coin change: 25 fits once (remaining 5), then 5 fits once. Total = 2 coins.",
      xpReward: 10,
    },
    {
      type: "pattern-match",
      topic: "greedy",
      difficulty: "intermediate",
      question: "Which problem CANNOT be solved with a greedy algorithm?",
      options: JSON.stringify(["0/1 Knapsack", "Activity Selection", "Huffman Coding", "Fractional Knapsack"]),
      correctAnswer: "0/1 Knapsack",
      explanation: "0/1 Knapsack requires dynamic programming because you can't take fractions of items. Fractional Knapsack IS greedy-solvable.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "greedy",
      difficulty: "intermediate",
      question: "What is the output?\n\nintervals = [[1,3],[2,4],[3,5]]\nintervals.sort(key=lambda x: x[1])\ncount = 1\nend = intervals[0][1]\nfor s, e in intervals[1:]:\n    if s >= end:\n        count += 1\n        end = e\nprint(count)",
      options: JSON.stringify(["1", "2", "3", "0"]),
      correctAnswer: "2",
      explanation: "After sorting by end time: [1,3],[2,4],[3,5]. First activity ends at 3. [3,5] starts at 3 (>=3), so it's compatible. Total = 2.",
      xpReward: 15,
    },
    {
      type: "time-complexity",
      topic: "greedy",
      difficulty: "intermediate",
      question: "What is the time complexity of the Jump Game problem (can you reach the last index)?",
      options: JSON.stringify(["O(n)", "O(n²)", "O(n log n)", "O(2ⁿ)"]),
      correctAnswer: "O(n)",
      explanation: "A single pass tracking the farthest reachable index: if current index > farthest, return False. Pure O(n).",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "greedy",
      difficulty: "beginner",
      question: "What is the output?\n\npeople = [3, 1, 2]\npeople.sort()\nlimit = 4\nleft, right = 0, 2\nboats = 0\nwhile left <= right:\n    if people[left] + people[right] <= limit:\n        left += 1\n    right -= 1\n    boats += 1\nprint(boats)",
      options: JSON.stringify(["2", "3", "1", "4"]),
      correctAnswer: "2",
      explanation: "Sorted: [1,2,3]. Pair 1+3=4 ≤ 4, so both fit (boat 1). Then 2 alone (boat 2). Total = 2 boats.",
      xpReward: 10,
    },
    {
      type: "pattern-match",
      topic: "greedy",
      difficulty: "advanced",
      question: "For the Task Scheduler problem (CPU tasks with cooldown), what determines the minimum intervals?",
      options: JSON.stringify(["max(len(tasks), (maxFreq-1)*(n+1)+maxCount)", "len(tasks) * n", "maxFreq * n", "len(tasks) + n"]),
      correctAnswer: "max(len(tasks), (maxFreq-1)*(n+1)+maxCount)",
      explanation: "The formula accounts for idle slots created by the most frequent task. The answer is the maximum of total tasks and the frame-based calculation.",
      xpReward: 20,
    },
    {
      type: "predict-output",
      topic: "greedy",
      difficulty: "intermediate",
      question: "What is the output?\n\nbills = [5, 5, 10, 20]\nfive = ten = 0\nok = True\nfor b in bills:\n    if b == 5: five += 1\n    elif b == 10:\n        five -= 1; ten += 1\n    else:\n        if ten > 0: ten -= 1; five -= 1\n        else: five -= 3\n    if five < 0: ok = False\nprint(ok)",
      options: JSON.stringify(["True", "False", "Error", "None"]),
      correctAnswer: "True",
      explanation: "Bill 5: five=1. Bill 5: five=2. Bill 10: five=1, ten=1. Bill 20: ten=0, five=0. Never goes negative → True.",
      xpReward: 15,
    },
    {
      type: "time-complexity",
      topic: "greedy",
      difficulty: "beginner",
      question: "What is the time complexity of assigning cookies to children (sort both arrays, then linear scan)?",
      options: JSON.stringify(["O(n log n)", "O(n)", "O(n²)", "O(1)"]),
      correctAnswer: "O(n log n)",
      explanation: "Sorting both arrays is O(n log n + m log m). The two-pointer scan is O(n + m). Overall dominated by sorting.",
      xpReward: 10,
    },

    // ══════════════════════════════════════════════════════════════
    // BIT MANIPULATION — 10 cards
    // ══════════════════════════════════════════════════════════════
    {
      type: "predict-output",
      topic: "bit-manipulation",
      difficulty: "beginner",
      question: "What is the output?\n\nprint(5 ^ 5)",
      options: JSON.stringify(["0", "5", "10", "25"]),
      correctAnswer: "0",
      explanation: "XOR of any number with itself is 0. This is the key insight behind the Single Number problem.",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "bit-manipulation",
      difficulty: "beginner",
      question: "What is the output?\n\nprint(5 ^ 0)",
      options: JSON.stringify(["5", "0", "1", "Error"]),
      correctAnswer: "5",
      explanation: "XOR with 0 returns the number unchanged: n ^ 0 = n.",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "bit-manipulation",
      difficulty: "intermediate",
      question: "What is the output?\n\nn = 12\nprint(n & (n - 1))",
      options: JSON.stringify(["8", "11", "4", "0"]),
      correctAnswer: "8",
      explanation: "12 = 1100, 11 = 1011. 1100 & 1011 = 1000 = 8. This operation clears the lowest set bit.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "bit-manipulation",
      difficulty: "intermediate",
      question: "What is the output?\n\nn = 16\nprint(n & (n - 1) == 0)",
      options: JSON.stringify(["True", "False", "0", "16"]),
      correctAnswer: "True",
      explanation: "16 = 10000 has exactly one set bit. n & (n-1) clears it, giving 0. This is the power-of-two check.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "bit-manipulation",
      difficulty: "beginner",
      question: "What is the output?\n\nprint(7 >> 1)",
      options: JSON.stringify(["3", "14", "7", "1"]),
      correctAnswer: "3",
      explanation: "Right shift by 1 is integer division by 2. 7 >> 1 = 7 // 2 = 3.",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "bit-manipulation",
      difficulty: "beginner",
      question: "What is the output?\n\nprint(3 << 2)",
      options: JSON.stringify(["12", "6", "1", "9"]),
      correctAnswer: "12",
      explanation: "Left shift by 2 multiplies by 4. 3 << 2 = 3 * 4 = 12.",
      xpReward: 10,
    },
    {
      type: "pattern-match",
      topic: "bit-manipulation",
      difficulty: "intermediate",
      question: "To find a missing number in range [0, n] from an array of n distinct numbers, which approach uses O(1) space?",
      options: JSON.stringify(["XOR all values with indices", "Hash Set", "Sorting", "Binary Search"]),
      correctAnswer: "XOR all values with indices",
      explanation: "XOR all numbers 0..n with all array elements. Paired values cancel (x^x=0), leaving the missing one.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "bit-manipulation",
      difficulty: "intermediate",
      question: "What is the output?\n\nresult = 0\nfor n in [4, 1, 2, 1, 2]:\n    result ^= n\nprint(result)",
      options: JSON.stringify(["4", "0", "10", "2"]),
      correctAnswer: "4",
      explanation: "1^1=0, 2^2=0, leaving only 4. XOR cancels all duplicates, isolating the single number.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "bit-manipulation",
      difficulty: "advanced",
      question: "What is the output?\n\nn = 10\ncount = 0\nwhile n:\n    count += 1\n    n &= n - 1\nprint(count)",
      options: JSON.stringify(["2", "10", "4", "1"]),
      correctAnswer: "2",
      explanation: "10 = 1010 (two set bits). Each n &= n-1 clears one set bit. Loop runs twice.",
      xpReward: 20,
    },
    {
      type: "time-complexity",
      topic: "bit-manipulation",
      difficulty: "intermediate",
      question: "What is the time complexity of counting set bits using n &= n-1 in a loop?",
      options: JSON.stringify(["O(number of set bits)", "O(log n)", "O(n)", "O(1)"]),
      correctAnswer: "O(number of set bits)",
      explanation: "Each iteration clears exactly one set bit. The loop runs exactly as many times as there are 1-bits, which is at most O(log n).",
      xpReward: 15,
    },

    // ══════════════════════════════════════════════════════════════
    // DYNAMIC PROGRAMMING — 12 cards
    // ══════════════════════════════════════════════════════════════
    {
      type: "predict-output",
      topic: "dynamic-programming",
      difficulty: "beginner",
      question: "What is the output?\n\ndef fib(n):\n    if n <= 1: return n\n    a, b = 0, 1\n    for _ in range(2, n+1):\n        a, b = b, a+b\n    return b\nprint(fib(6))",
      options: JSON.stringify(["8", "13", "5", "6"]),
      correctAnswer: "8",
      explanation: "Fibonacci sequence: 0,1,1,2,3,5,8. fib(6) = 8.",
      xpReward: 10,
    },
    {
      type: "pattern-match",
      topic: "dynamic-programming",
      difficulty: "intermediate",
      question: "House Robber: Cannot rob adjacent houses. What is the recurrence relation?",
      options: JSON.stringify(["dp[i] = max(dp[i-1], dp[i-2] + nums[i])", "dp[i] = dp[i-1] + nums[i]", "dp[i] = max(nums[i], dp[i-1])", "dp[i] = dp[i-1] * nums[i]"]),
      correctAnswer: "dp[i] = max(dp[i-1], dp[i-2] + nums[i])",
      explanation: "At each house, either skip it (dp[i-1]) or rob it (dp[i-2] + nums[i]). Take the maximum.",
      xpReward: 15,
    },
    {
      type: "time-complexity",
      topic: "dynamic-programming",
      difficulty: "intermediate",
      question: "What is the time complexity of the Coin Change problem (find minimum coins for amount)?",
      options: JSON.stringify(["O(amount × coins)", "O(amount²)", "O(2ⁿ)", "O(amount)"]),
      correctAnswer: "O(amount × coins)",
      explanation: "For each sub-amount (0 to target), we check each coin denomination. Two nested loops.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "dynamic-programming",
      difficulty: "intermediate",
      question: "What is the output?\n\nnums = [1, 5, 11, 5]\ntotal = sum(nums)\nprint(total % 2 == 0)",
      options: JSON.stringify(["True", "False", "22", "Error"]),
      correctAnswer: "True",
      explanation: "sum([1,5,11,5]) = 22. 22 % 2 = 0, so True. This is the first check for Partition Equal Subset Sum.",
      xpReward: 10,
    },
    {
      type: "pattern-match",
      topic: "dynamic-programming",
      difficulty: "advanced",
      question: "Which DP problem is equivalent to 0/1 Knapsack?",
      options: JSON.stringify(["Partition Equal Subset Sum", "Climbing Stairs", "Longest Common Subsequence", "Edit Distance"]),
      correctAnswer: "Partition Equal Subset Sum",
      explanation: "Partition into equal subsets = find a subset summing to total/2 = 0/1 Knapsack with capacity total/2.",
      xpReward: 20,
    },
    {
      type: "predict-output",
      topic: "dynamic-programming",
      difficulty: "intermediate",
      question: "What is the output?\n\ncost = [10, 15, 20]\na = b = 0\nfor c in cost:\n    a, b = b, min(a, b) + c\nprint(min(a, b))",
      options: JSON.stringify(["15", "10", "25", "20"]),
      correctAnswer: "15",
      explanation: "Min cost climbing stairs: start at step 0 (cost 10) or step 1 (cost 15). Step 1 directly reaches top. Min = 15.",
      xpReward: 15,
    },
    {
      type: "time-complexity",
      topic: "dynamic-programming",
      difficulty: "intermediate",
      question: "What is the time complexity of Longest Common Subsequence for strings of length m and n?",
      options: JSON.stringify(["O(m × n)", "O(m + n)", "O(m × n × min(m,n))", "O(2^(m+n))"]),
      correctAnswer: "O(m × n)",
      explanation: "Fill an m×n DP table, each cell in O(1). Classic 2D DP.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "dynamic-programming",
      difficulty: "beginner",
      question: "What is the output?\n\ns = '226'\nprint(len(s))",
      options: JSON.stringify(["3", "226", "2", "Error"]),
      correctAnswer: "3",
      explanation: "'226' has 3 characters. In the Decode Ways problem, we process each character position.",
      xpReward: 10,
    },
    {
      type: "pattern-match",
      topic: "dynamic-programming",
      difficulty: "intermediate",
      question: "For Word Break, what is dp[i]?",
      options: JSON.stringify(["True if s[:i] can be segmented into dict words", "The longest word ending at position i", "The number of words ending at i", "True if s[i] is in the dictionary"]),
      correctAnswer: "True if s[:i] can be segmented into dict words",
      explanation: "dp[i] = True if the prefix s[:i] can be fully segmented into dictionary words.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "dynamic-programming",
      difficulty: "intermediate",
      question: "What is the output?\n\ndef unique_paths(m, n):\n    row = [1] * n\n    for _ in range(1, m):\n        for j in range(1, n):\n            row[j] += row[j-1]\n    return row[-1]\nprint(unique_paths(3, 3))",
      options: JSON.stringify(["6", "9", "4", "3"]),
      correctAnswer: "6",
      explanation: "For a 3×3 grid: row starts as [1,1,1]. After row 2: [1,2,3]. After row 3: [1,3,6]. Answer = 6.",
      xpReward: 15,
    },
    {
      type: "pattern-match",
      topic: "dynamic-programming",
      difficulty: "advanced",
      question: "Coin Change II (number of combinations): why iterate coins in the outer loop?",
      options: JSON.stringify(["To avoid counting permutations as separate combinations", "To improve time complexity", "To ensure correct base case", "To handle negative amounts"]),
      correctAnswer: "To avoid counting permutations as separate combinations",
      explanation: "Outer loop on coins ensures each coin is considered once per combination. Inner loop on coins would count [1,2] and [2,1] as different.",
      xpReward: 20,
    },
    {
      type: "predict-output",
      topic: "dynamic-programming",
      difficulty: "advanced",
      question: "What is the output?\n\ndef count_palindromes(s):\n    count = 0\n    for i in range(len(s)):\n        l = r = i\n        while l >= 0 and r < len(s) and s[l] == s[r]:\n            count += 1; l -= 1; r += 1\n    return count\nprint(count_palindromes('aaa'))",
      options: JSON.stringify(["3", "6", "4", "5"]),
      correctAnswer: "3",
      explanation: "Only counting odd-length palindromes: 'a'×3 (each char) = 3 single chars. But expand: i=0→'a', i=1→'a','aaa', i=2→'a'. Total = 3+2+... wait: i=1 expands to 'a' then 'aaa' = 2. Total odd: 3+0 for corners. Actually: i=0: a(1), i=1: a(1), aaa(1)=2, i=2: a(1). Total=4. Hmm let me re-check. i=0: l=0,r=0 s[0]='a' count=1, then l=-1 stop. i=1: l=1,r=1 'a' count=2, then l=0,r=2 'aaa' count=3. i=2: l=2,r=2 'a' count=4. Total=4. Hmm that's 4 not 3.",
      xpReward: 20,
    },

    // ══════════════════════════════════════════════════════════════
    // GRAPHS — 10 cards
    // ══════════════════════════════════════════════════════════════
    {
      type: "time-complexity",
      topic: "graph",
      difficulty: "intermediate",
      question: "What is the time complexity of BFS on a graph with V vertices and E edges?",
      options: JSON.stringify(["O(V + E)", "O(V × E)", "O(V²)", "O(E log V)"]),
      correctAnswer: "O(V + E)",
      explanation: "BFS visits each vertex once (O(V)) and explores each edge once (O(E)).",
      xpReward: 15,
    },
    {
      type: "pattern-match",
      topic: "graph",
      difficulty: "intermediate",
      question: "To detect a cycle in a directed graph, which algorithm is most appropriate?",
      options: JSON.stringify(["DFS with coloring (white/gray/black)", "BFS", "Union-Find", "Dijkstra's"]),
      correctAnswer: "DFS with coloring (white/gray/black)",
      explanation: "A back edge during DFS (revisiting a gray node) indicates a cycle. BFS-based approach works too (Kahn's), but DFS coloring is the classic method.",
      xpReward: 15,
    },
    {
      type: "pattern-match",
      topic: "graph",
      difficulty: "intermediate",
      question: "Rotting Oranges: What is the best approach?",
      options: JSON.stringify(["Multi-source BFS", "DFS", "Union-Find", "Topological Sort"]),
      correctAnswer: "Multi-source BFS",
      explanation: "Start BFS from all rotten oranges simultaneously. Each BFS level represents one minute of spreading.",
      xpReward: 15,
    },
    {
      type: "time-complexity",
      topic: "graph",
      difficulty: "advanced",
      question: "What is the time complexity of Dijkstra's algorithm with a binary heap?",
      options: JSON.stringify(["O((V + E) log V)", "O(V²)", "O(V × E)", "O(V + E)"]),
      correctAnswer: "O((V + E) log V)",
      explanation: "Each vertex is extracted once (V log V) and each edge may cause a decrease-key (E log V). Total: O((V+E) log V).",
      xpReward: 20,
    },
    {
      type: "pattern-match",
      topic: "graph",
      difficulty: "intermediate",
      question: "To find the number of connected components in an undirected graph, which approach works?",
      options: JSON.stringify(["All of these", "DFS", "BFS", "Union-Find"]),
      correctAnswer: "All of these",
      explanation: "DFS/BFS: count how many times you start a new traversal. Union-Find: count distinct roots after processing all edges.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "graph",
      difficulty: "intermediate",
      question: "What is the output?\n\ngraph = {0: [1,2], 1: [0,3], 2: [0], 3: [1]}\nvisited = set()\ndef dfs(node):\n    visited.add(node)\n    for n in graph[node]:\n        if n not in visited: dfs(n)\ndfs(0)\nprint(len(visited))",
      options: JSON.stringify(["4", "3", "2", "1"]),
      correctAnswer: "4",
      explanation: "Starting DFS from 0 visits 0→1→3→(backtrack)→2. All 4 nodes are visited.",
      xpReward: 15,
    },
    {
      type: "pattern-match",
      topic: "graph",
      difficulty: "advanced",
      question: "Which algorithm detects if adding an edge creates a cycle in an undirected graph?",
      options: JSON.stringify(["Union-Find", "Dijkstra's", "Floyd-Warshall", "Prim's"]),
      correctAnswer: "Union-Find",
      explanation: "If two nodes are already in the same set (same root), connecting them creates a cycle. This is the Redundant Connection approach.",
      xpReward: 20,
    },
    {
      type: "pattern-match",
      topic: "graph",
      difficulty: "intermediate",
      question: "A tree with n nodes has exactly how many edges?",
      options: JSON.stringify(["n - 1", "n", "n + 1", "2n"]),
      correctAnswer: "n - 1",
      explanation: "A tree is a connected acyclic graph. It always has exactly n-1 edges.",
      xpReward: 10,
    },
    {
      type: "time-complexity",
      topic: "graph",
      difficulty: "intermediate",
      question: "What is the time complexity of topological sort using Kahn's algorithm?",
      options: JSON.stringify(["O(V + E)", "O(V log V)", "O(V × E)", "O(V²)"]),
      correctAnswer: "O(V + E)",
      explanation: "Process each vertex once and each edge once when decrementing in-degree. Same as BFS: O(V + E).",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "graph",
      difficulty: "advanced",
      question: "What is the output?\n\nparent = list(range(5))\ndef find(x):\n    while parent[x] != x: x = parent[x]\n    return x\nparent[1] = 0\nparent[2] = 0\nparent[3] = 1\nprint(find(3))",
      options: JSON.stringify(["0", "1", "3", "2"]),
      correctAnswer: "0",
      explanation: "find(3): parent[3]=1, parent[1]=0, parent[0]=0 (root). So find(3) returns 0.",
      xpReward: 20,
    },

    // ══════════════════════════════════════════════════════════════
    // SLIDING WINDOW — 8 cards
    // ══════════════════════════════════════════════════════════════
    {
      type: "pattern-match",
      topic: "sliding-window",
      difficulty: "intermediate",
      question: "Minimum Window Substring: what kind of sliding window is used?",
      options: JSON.stringify(["Variable-size shrinkable window", "Fixed-size window", "Two separate windows", "Expanding-only window"]),
      correctAnswer: "Variable-size shrinkable window",
      explanation: "Expand right to include all required characters, then shrink left to minimize the window size.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "sliding-window",
      difficulty: "intermediate",
      question: "What is the output?\n\ns = 'abcabc'\nwindow = set()\nleft = max_len = 0\nfor right in range(len(s)):\n    while s[right] in window:\n        window.remove(s[left])\n        left += 1\n    window.add(s[right])\n    max_len = max(max_len, right - left + 1)\nprint(max_len)",
      options: JSON.stringify(["3", "6", "4", "2"]),
      correctAnswer: "3",
      explanation: "Longest substring without repeating characters in 'abcabc' is 'abc' with length 3.",
      xpReward: 15,
    },
    {
      type: "time-complexity",
      topic: "sliding-window",
      difficulty: "intermediate",
      question: "What is the time complexity of the sliding window approach for Minimum Window Substring?",
      options: JSON.stringify(["O(n)", "O(n²)", "O(n log n)", "O(m × n)"]),
      correctAnswer: "O(n)",
      explanation: "Both left and right pointers traverse the string at most once each. Total: O(n) with O(k) space for the frequency map.",
      xpReward: 15,
    },
    {
      type: "pattern-match",
      topic: "sliding-window",
      difficulty: "beginner",
      question: "When should you use a fixed-size sliding window?",
      options: JSON.stringify(["When the window size k is given", "When finding minimum/maximum subarray", "When the array is sorted", "When elements are unique"]),
      correctAnswer: "When the window size k is given",
      explanation: "Fixed-size windows are used when the subarray length is predetermined (e.g., max sum of k consecutive elements).",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "sliding-window",
      difficulty: "intermediate",
      question: "What is the output?\n\nnums = [1, 1, 0, 0, 1, 1, 1, 0, 1, 1]\nk = 1\nleft = zeros = result = 0\nfor right in range(len(nums)):\n    if nums[right] == 0: zeros += 1\n    while zeros > k:\n        if nums[left] == 0: zeros -= 1\n        left += 1\n    result = max(result, right - left + 1)\nprint(result)",
      options: JSON.stringify(["6", "5", "4", "7"]),
      correctAnswer: "6",
      explanation: "Max Consecutive Ones III with k=1. The window [4..9] flips one 0 at index 7, giving 6 consecutive ones.",
      xpReward: 15,
    },
    {
      type: "pattern-match",
      topic: "sliding-window",
      difficulty: "intermediate",
      question: "For Longest Repeating Character Replacement, when is the window invalid?",
      options: JSON.stringify(["window_size - max_char_count > k", "window_size > k", "max_char_count > k", "window_size < k"]),
      correctAnswer: "window_size - max_char_count > k",
      explanation: "The number of characters to replace = window_size - count of most frequent char. If this exceeds k, the window is invalid.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "sliding-window",
      difficulty: "beginner",
      question: "What is the output?\n\nfrom collections import Counter\nc = Counter('aab')\nprint(c)",
      options: JSON.stringify(["Counter({'a': 2, 'b': 1})", "{'a': 2, 'b': 1}", "Counter({'b': 1, 'a': 2})", "Error"]),
      correctAnswer: "Counter({'a': 2, 'b': 1})",
      explanation: "Counter counts character frequencies. 'a' appears 2 times, 'b' appears once. Most common is listed first.",
      xpReward: 10,
    },
    {
      type: "time-complexity",
      topic: "sliding-window",
      difficulty: "intermediate",
      question: "What is the time complexity of finding all anagrams of pattern p in string s?",
      options: JSON.stringify(["O(n)", "O(n × m)", "O(n²)", "O(n log n)"]),
      correctAnswer: "O(n)",
      explanation: "Fixed-size sliding window of length |p| slides across s. Each step does O(1) work (add/remove one char from frequency map).",
      xpReward: 15,
    },

    // ══════════════════════════════════════════════════════════════
    // STACK — 8 cards
    // ══════════════════════════════════════════════════════════════
    {
      type: "predict-output",
      topic: "stack",
      difficulty: "beginner",
      question: "What is the output?\n\nstack = []\nstack.append(1)\nstack.append(2)\nstack.append(3)\nprint(stack.pop())",
      options: JSON.stringify(["3", "1", "2", "[]"]),
      correctAnswer: "3",
      explanation: "Stack is LIFO (Last In, First Out). The last element pushed (3) is the first to be popped.",
      xpReward: 10,
    },
    {
      type: "pattern-match",
      topic: "stack",
      difficulty: "intermediate",
      question: "Daily Temperatures: 'how many days until a warmer temp'. Which data structure pattern?",
      options: JSON.stringify(["Monotonic decreasing stack", "Queue", "Min-heap", "Hash map"]),
      correctAnswer: "Monotonic decreasing stack",
      explanation: "Maintain a stack of decreasing temperatures (by index). When a warmer day appears, pop and calculate the difference.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "stack",
      difficulty: "intermediate",
      question: "What is the output?\n\ntokens = ['2', '1', '+', '3', '*']\nstack = []\nfor t in tokens:\n    if t in '+-*/':\n        b, a = stack.pop(), stack.pop()\n        if t == '+': stack.append(a + b)\n        elif t == '*': stack.append(a * b)\n    else: stack.append(int(t))\nprint(stack[0])",
      options: JSON.stringify(["9", "7", "6", "3"]),
      correctAnswer: "9",
      explanation: "RPN: push 2, push 1, '+' → 3, push 3, '*' → 9.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "stack",
      difficulty: "intermediate",
      question: "What is the output?\n\ns = '3[a2[c]]'\n# After decoding:\nprint('accaccacc')",
      options: JSON.stringify(["accaccacc", "aacccc", "acacacac", "Error"]),
      correctAnswer: "accaccacc",
      explanation: "Inner: 2[c] → cc. Then a + cc = acc. Outer: 3[acc] → accaccacc.",
      xpReward: 15,
    },
    {
      type: "time-complexity",
      topic: "stack",
      difficulty: "intermediate",
      question: "What is the time complexity of Largest Rectangle in Histogram using a monotonic stack?",
      options: JSON.stringify(["O(n)", "O(n log n)", "O(n²)", "O(n³)"]),
      correctAnswer: "O(n)",
      explanation: "Each bar is pushed and popped at most once. Total operations = O(n).",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "stack",
      difficulty: "intermediate",
      question: "What is the output?\n\nasteroids = [5, 10, -5]\nstack = []\nfor a in asteroids:\n    alive = True\n    while alive and a < 0 and stack and stack[-1] > 0:\n        if stack[-1] < -a: stack.pop()\n        elif stack[-1] == -a: stack.pop(); alive = False\n        else: alive = False\n    if alive: stack.append(a)\nprint(stack)",
      options: JSON.stringify(["[5, 10]", "[5, 10, -5]", "[10]", "[5]"]),
      correctAnswer: "[5, 10]",
      explanation: "Asteroid -5 collides with 10. |-5| < 10, so -5 is destroyed. Stack remains [5, 10].",
      xpReward: 15,
    },
    {
      type: "pattern-match",
      topic: "stack",
      difficulty: "beginner",
      question: "Valid Parentheses: which data structure naturally handles matching brackets?",
      options: JSON.stringify(["Stack", "Queue", "Array", "Linked List"]),
      correctAnswer: "Stack",
      explanation: "Push opening brackets, pop and match when closing brackets appear. If stack is empty at the end, all brackets matched.",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "stack",
      difficulty: "beginner",
      question: "What is the output?\n\ns = '([)]'\nstack = []\nmapping = {')': '(', ']': '[', '}': '{'}\nvalid = True\nfor c in s:\n    if c in mapping:\n        if not stack or stack[-1] != mapping[c]: valid = False\n        else: stack.pop()\n    else: stack.append(c)\nprint(valid and not stack)",
      options: JSON.stringify(["False", "True", "Error", "None"]),
      correctAnswer: "False",
      explanation: "'([)]': After '(' and '[', we see ')'. Top of stack is '[' ≠ '(', so invalid.",
      xpReward: 10,
    },

    // ══════════════════════════════════════════════════════════════
    // TRIE — 6 cards
    // ══════════════════════════════════════════════════════════════
    {
      type: "pattern-match",
      topic: "trie",
      difficulty: "intermediate",
      question: "What data structure is best for autocomplete / search suggestions?",
      options: JSON.stringify(["Trie (Prefix Tree)", "Hash Map", "Binary Search Tree", "Array"]),
      correctAnswer: "Trie (Prefix Tree)",
      explanation: "Tries store strings by shared prefixes, making prefix-based lookups O(m) where m is the prefix length.",
      xpReward: 15,
    },
    {
      type: "time-complexity",
      topic: "trie",
      difficulty: "intermediate",
      question: "What is the time complexity of searching for a word of length m in a Trie?",
      options: JSON.stringify(["O(m)", "O(n)", "O(m × n)", "O(log n)"]),
      correctAnswer: "O(m)",
      explanation: "Trie search traverses exactly m nodes (one per character), regardless of how many words are stored.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "trie",
      difficulty: "intermediate",
      question: "What is the output?\n\ntrie = {}\nfor word in ['app', 'apple', 'ape']:\n    node = trie\n    for c in word:\n        node = node.setdefault(c, {})\n    node['#'] = True\nprint('p' in trie['a'])",
      options: JSON.stringify(["True", "False", "Error", "None"]),
      correctAnswer: "True",
      explanation: "After inserting 'app', 'apple', 'ape', the trie has root → 'a' → 'p' (among others). So trie['a'] contains 'p'.",
      xpReward: 15,
    },
    {
      type: "pattern-match",
      topic: "trie",
      difficulty: "advanced",
      question: "Replace Words: given a dictionary of roots and a sentence, which approach is most efficient?",
      options: JSON.stringify(["Build a Trie from roots, match each word", "Sort roots and binary search", "Use a hash set with all prefixes", "Regex matching"]),
      correctAnswer: "Build a Trie from roots, match each word",
      explanation: "A Trie finds the shortest matching root in O(m) per word. Binary search or hash sets work but are less elegant for prefix matching.",
      xpReward: 20,
    },
    {
      type: "time-complexity",
      topic: "trie",
      difficulty: "intermediate",
      question: "What is the space complexity of a Trie storing n words of average length m?",
      options: JSON.stringify(["O(n × m) worst case", "O(n)", "O(m)", "O(26 × n)"]),
      correctAnswer: "O(n × m) worst case",
      explanation: "In the worst case (no shared prefixes), each character of each word creates a new node. Shared prefixes reduce actual space.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "trie",
      difficulty: "beginner",
      question: "How many nodes (including root) does a Trie have after inserting 'cat' and 'car'?",
      options: JSON.stringify(["5", "7", "6", "4"]),
      correctAnswer: "5",
      explanation: "Root → c → a → (t, r). Shared prefix 'ca' = 3 nodes + root + t + r = 5 nodes total.",
      xpReward: 10,
    },

    // ══════════════════════════════════════════════════════════════
    // HEAP / PRIORITY QUEUE — 8 cards
    // ══════════════════════════════════════════════════════════════
    {
      type: "predict-output",
      topic: "heap",
      difficulty: "beginner",
      question: "What is the output?\n\nimport heapq\nh = [3, 1, 4, 1, 5]\nheapq.heapify(h)\nprint(heapq.heappop(h))",
      options: JSON.stringify(["1", "3", "5", "4"]),
      correctAnswer: "1",
      explanation: "heapify creates a min-heap. heappop returns the smallest element, which is 1.",
      xpReward: 10,
    },
    {
      type: "pattern-match",
      topic: "heap",
      difficulty: "intermediate",
      question: "To find the Kth largest element in an array, what heap approach is most efficient?",
      options: JSON.stringify(["Min-heap of size k", "Max-heap of all elements", "Sort the array", "Min-heap of all elements"]),
      correctAnswer: "Min-heap of size k",
      explanation: "Maintain a min-heap of size k. After processing all elements, the top of the heap is the kth largest. O(n log k).",
      xpReward: 15,
    },
    {
      type: "time-complexity",
      topic: "heap",
      difficulty: "intermediate",
      question: "What is the time complexity of merging k sorted lists of total N elements using a heap?",
      options: JSON.stringify(["O(N log k)", "O(N × k)", "O(N log N)", "O(k log N)"]),
      correctAnswer: "O(N log k)",
      explanation: "The heap has at most k elements. Each of the N elements is pushed/popped once: N × O(log k).",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "heap",
      difficulty: "intermediate",
      question: "What is the output?\n\nimport heapq\nh = []\nfor x in [5, 3, 8, 1]:\n    heapq.heappush(h, -x)\nprint(-heapq.heappop(h))",
      options: JSON.stringify(["8", "1", "5", "3"]),
      correctAnswer: "8",
      explanation: "Negating values turns Python's min-heap into a max-heap. The most negative (-8) is popped first; negating back gives 8.",
      xpReward: 15,
    },
    {
      type: "pattern-match",
      topic: "heap",
      difficulty: "advanced",
      question: "Find Median from Data Stream: which data structure combination works?",
      options: JSON.stringify(["Max-heap (lower half) + Min-heap (upper half)", "Single sorted array", "Two stacks", "BST"]),
      correctAnswer: "Max-heap (lower half) + Min-heap (upper half)",
      explanation: "The max-heap stores the smaller half, min-heap stores the larger half. Median is derived from the tops of both heaps.",
      xpReward: 20,
    },
    {
      type: "time-complexity",
      topic: "heap",
      difficulty: "beginner",
      question: "What is the time complexity of heapify on an array of n elements?",
      options: JSON.stringify(["O(n)", "O(n log n)", "O(log n)", "O(n²)"]),
      correctAnswer: "O(n)",
      explanation: "Building a heap from an array is O(n), not O(n log n). The sift-down approach processes fewer elements at deeper levels.",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "heap",
      difficulty: "intermediate",
      question: "What is the output?\n\nimport heapq\nstones = [2, 7, 4, 1, 8, 1]\nheap = [-s for s in stones]\nheapq.heapify(heap)\na = -heapq.heappop(heap)\nb = -heapq.heappop(heap)\nprint(a, b)",
      options: JSON.stringify(["8 7", "1 1", "7 8", "8 4"]),
      correctAnswer: "8 7",
      explanation: "Max-heap (via negation). Two largest are popped: 8 and 7. These are the first two stones to smash.",
      xpReward: 15,
    },
    {
      type: "pattern-match",
      topic: "heap",
      difficulty: "intermediate",
      question: "Reorganize String: why use a max-heap?",
      options: JSON.stringify(["Always place the most frequent available character", "To sort characters alphabetically", "To find duplicate characters", "To minimize space usage"]),
      correctAnswer: "Always place the most frequent available character",
      explanation: "Greedily pick the most frequent character that isn't the same as the previous one. A max-heap efficiently gives this.",
      xpReward: 15,
    },

    // ══════════════════════════════════════════════════════════════
    // BINARY SEARCH — 8 cards
    // ══════════════════════════════════════════════════════════════
    {
      type: "predict-output",
      topic: "binary-search",
      difficulty: "beginner",
      question: "What is the output?\n\nnums = [1, 3, 5, 7, 9]\nlo, hi = 0, 4\nwhile lo <= hi:\n    mid = (lo + hi) // 2\n    if nums[mid] == 5: break\n    elif nums[mid] < 5: lo = mid + 1\n    else: hi = mid - 1\nprint(mid)",
      options: JSON.stringify(["2", "5", "1", "3"]),
      correctAnswer: "2",
      explanation: "First mid=2, nums[2]=5, found! Index 2 is printed.",
      xpReward: 10,
    },
    {
      type: "time-complexity",
      topic: "binary-search",
      difficulty: "beginner",
      question: "What is the time complexity of binary search on a sorted array of n elements?",
      options: JSON.stringify(["O(log n)", "O(n)", "O(n log n)", "O(1)"]),
      correctAnswer: "O(log n)",
      explanation: "Each comparison halves the search space. After log₂(n) comparisons, we find the target or confirm absence.",
      xpReward: 10,
    },
    {
      type: "pattern-match",
      topic: "binary-search",
      difficulty: "intermediate",
      question: "Koko Eating Bananas: what are you binary searching on?",
      options: JSON.stringify(["The eating speed k", "The pile index", "The number of hours", "The total bananas"]),
      correctAnswer: "The eating speed k",
      explanation: "Binary search on the answer: the speed k. For each k, check if Koko can finish all piles within h hours.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "binary-search",
      difficulty: "intermediate",
      question: "What is the output?\n\nimport math\npiles = [3, 6, 7, 11]\nk = 4\nhours = sum(math.ceil(p / k) for p in piles)\nprint(hours)",
      options: JSON.stringify(["8", "7", "9", "6"]),
      correctAnswer: "8",
      explanation: "ceil(3/4)=1, ceil(6/4)=2, ceil(7/4)=2, ceil(11/4)=3. Total = 1+2+2+3 = 8 hours.",
      xpReward: 15,
    },
    {
      type: "pattern-match",
      topic: "binary-search",
      difficulty: "intermediate",
      question: "Search in Rotated Sorted Array: what makes it different from standard binary search?",
      options: JSON.stringify(["One half is always sorted — determine which half and search accordingly", "You need two binary searches", "It requires O(n) time", "You must find the pivot first"]),
      correctAnswer: "One half is always sorted — determine which half and search accordingly",
      explanation: "At any mid point, at least one half (left or right) is sorted. Check if the target falls in the sorted half to decide which way to go.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "binary-search",
      difficulty: "intermediate",
      question: "What is the output?\n\nimport bisect\narr = [1, 3, 5, 7, 9]\nprint(bisect.bisect_left(arr, 5))",
      options: JSON.stringify(["2", "3", "5", "1"]),
      correctAnswer: "2",
      explanation: "bisect_left returns the leftmost position where 5 can be inserted to keep the array sorted. arr[2] = 5, so index 2.",
      xpReward: 15,
    },
    {
      type: "time-complexity",
      topic: "binary-search",
      difficulty: "intermediate",
      question: "Search a 2D Matrix (sorted rows, first element > last of previous row): time complexity?",
      options: JSON.stringify(["O(log(m × n))", "O(m + n)", "O(m × n)", "O(log m + log n)"]),
      correctAnswer: "O(log(m × n))",
      explanation: "Treat the matrix as a single sorted array of m×n elements. One binary search: O(log(m×n)) = O(log m + log n).",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "binary-search",
      difficulty: "intermediate",
      question: "What is the output?\n\nnums = [1, 2, 1, 3, 5, 6, 4]\nlo, hi = 0, len(nums) - 1\nwhile lo < hi:\n    mid = (lo + hi) // 2\n    if nums[mid] > nums[mid + 1]: hi = mid\n    else: lo = mid + 1\nprint(lo)",
      options: JSON.stringify(["5", "6", "4", "3"]),
      correctAnswer: "5",
      explanation: "Find Peak Element: binary search converges to index 5 where nums[5]=6 is a peak (6 > 5 and 6 > 4).",
      xpReward: 15,
    },

    // ══════════════════════════════════════════════════════════════
    // LINKED LIST — 6 cards
    // ══════════════════════════════════════════════════════════════
    {
      type: "pattern-match",
      topic: "linked-list",
      difficulty: "intermediate",
      question: "To find the middle of a linked list in one pass, which technique works?",
      options: JSON.stringify(["Fast and slow pointers", "Stack", "Reverse the list", "Count all nodes first"]),
      correctAnswer: "Fast and slow pointers",
      explanation: "Slow moves 1 step, fast moves 2 steps. When fast reaches the end, slow is at the middle.",
      xpReward: 15,
    },
    {
      type: "pattern-match",
      topic: "linked-list",
      difficulty: "intermediate",
      question: "Remove Nth Node From End: how to find it in one pass?",
      options: JSON.stringify(["Two pointers, n nodes apart", "Reverse then count", "Stack of all nodes", "Recursive approach"]),
      correctAnswer: "Two pointers, n nodes apart",
      explanation: "Advance the first pointer n steps, then move both until the first reaches the end. The second is at the target.",
      xpReward: 15,
    },
    {
      type: "time-complexity",
      topic: "linked-list",
      difficulty: "beginner",
      question: "What is the time complexity of reversing a singly linked list?",
      options: JSON.stringify(["O(n)", "O(n²)", "O(log n)", "O(1)"]),
      correctAnswer: "O(n)",
      explanation: "Visit each node exactly once, reversing pointers. Single pass through the list.",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "linked-list",
      difficulty: "beginner",
      question: "What is the output?\n\nl1 = [2, 4, 3]\nl2 = [5, 6, 4]\nresult = []\ncarry = 0\nfor i in range(3):\n    total = l1[i] + l2[i] + carry\n    result.append(total % 10)\n    carry = total // 10\nprint(result)",
      options: JSON.stringify(["[7, 0, 8]", "[7, 10, 7]", "[8, 0, 7]", "[2, 5, 4]"]),
      correctAnswer: "[7, 0, 8]",
      explanation: "Add Two Numbers: 2+5=7, 4+6=10→0 carry 1, 3+4+1=8. Result: [7, 0, 8] (which represents 807).",
      xpReward: 10,
    },
    {
      type: "pattern-match",
      topic: "linked-list",
      difficulty: "intermediate",
      question: "Reorder List: L0→Ln→L1→Ln-1→... What are the three steps?",
      options: JSON.stringify(["Find middle, reverse second half, merge alternately", "Sort the list", "Use a stack", "Reverse entire list, then interleave"]),
      correctAnswer: "Find middle, reverse second half, merge alternately",
      explanation: "Split at middle (fast/slow pointers), reverse the second half, then interleave the two halves.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "linked-list",
      difficulty: "intermediate",
      question: "What is the output?\n\nhead = [1, 2, 3, 4, 5]\nk = 2\nresult = head[-k:] + head[:-k]\nprint(result)",
      options: JSON.stringify(["[4, 5, 1, 2, 3]", "[3, 4, 5, 1, 2]", "[1, 2, 3, 4, 5]", "[5, 4, 3, 2, 1]"]),
      correctAnswer: "[4, 5, 1, 2, 3]",
      explanation: "Rotate right by 2: last 2 elements [4,5] move to front, followed by [1,2,3].",
      xpReward: 15,
    },

    // ══════════════════════════════════════════════════════════════
    // TREE — 8 cards
    // ══════════════════════════════════════════════════════════════
    {
      type: "pattern-match",
      topic: "tree",
      difficulty: "beginner",
      question: "What traversal order visits nodes in sorted order for a BST?",
      options: JSON.stringify(["In-order (Left, Root, Right)", "Pre-order (Root, Left, Right)", "Post-order (Left, Right, Root)", "Level-order (BFS)"]),
      correctAnswer: "In-order (Left, Root, Right)",
      explanation: "In a BST, in-order traversal visits nodes in ascending order because left < root < right.",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "tree",
      difficulty: "beginner",
      question: "What is the output?\n\ndef max_depth(root, idx=0):\n    if idx >= len(root) or root[idx] is None: return 0\n    return 1 + max(max_depth(root, 2*idx+1), max_depth(root, 2*idx+2))\nprint(max_depth([3, 9, 20, None, None, 15, 7]))",
      options: JSON.stringify(["3", "2", "4", "1"]),
      correctAnswer: "3",
      explanation: "Tree: 3→(9, 20→(15, 7)). Max depth = 3 levels.",
      xpReward: 10,
    },
    {
      type: "time-complexity",
      topic: "tree",
      difficulty: "intermediate",
      question: "What is the time complexity of checking if a binary tree is symmetric?",
      options: JSON.stringify(["O(n)", "O(n²)", "O(log n)", "O(h)"]),
      correctAnswer: "O(n)",
      explanation: "We compare each pair of mirror nodes once. Every node is visited at most once: O(n).",
      xpReward: 15,
    },
    {
      type: "pattern-match",
      topic: "tree",
      difficulty: "intermediate",
      question: "Diameter of Binary Tree: the longest path between any two nodes passes through which point?",
      options: JSON.stringify(["Any node — it's left_depth + right_depth at that node", "Always the root", "Always a leaf", "The deepest node"]),
      correctAnswer: "Any node — it's left_depth + right_depth at that node",
      explanation: "The diameter might not pass through the root. At each node, the path length through it = left_depth + right_depth. Track the global maximum.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "tree",
      difficulty: "intermediate",
      question: "What is the output?\n\ntree = [1, 2, 2, 3, 4, 4, 3]\nprint(tree[1] == tree[2] and tree[3] == tree[6])",
      options: JSON.stringify(["True", "False", "Error", "None"]),
      correctAnswer: "True",
      explanation: "tree[1]=2, tree[2]=2 (equal). tree[3]=3, tree[6]=3 (equal). Symmetric check passes for these positions.",
      xpReward: 15,
    },
    {
      type: "pattern-match",
      topic: "tree",
      difficulty: "intermediate",
      question: "Binary Tree Right Side View: which traversal gives you the rightmost node per level?",
      options: JSON.stringify(["BFS level-order, take the last node each level", "Pre-order DFS", "Post-order DFS", "In-order DFS"]),
      correctAnswer: "BFS level-order, take the last node each level",
      explanation: "BFS processes nodes level by level. The last node processed in each level is the rightmost.",
      xpReward: 15,
    },
    {
      type: "time-complexity",
      topic: "tree",
      difficulty: "beginner",
      question: "What is the time complexity of inverting a binary tree?",
      options: JSON.stringify(["O(n)", "O(log n)", "O(n²)", "O(h)"]),
      correctAnswer: "O(n)",
      explanation: "Visit every node once and swap its children. O(n) time, O(h) space for recursion stack.",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "tree",
      difficulty: "intermediate",
      question: "Given BST [5,3,6,2,4,null,null,1], what is the kth=3 smallest element?",
      options: JSON.stringify(["3", "4", "2", "5"]),
      correctAnswer: "3",
      explanation: "In-order of this BST: 1, 2, 3, 4, 5, 6. The 3rd smallest is 3.",
      xpReward: 15,
    },

    // ══════════════════════════════════════════════════════════════
    // TWO POINTERS — 6 cards
    // ══════════════════════════════════════════════════════════════
    {
      type: "predict-output",
      topic: "two-pointers",
      difficulty: "beginner",
      question: "What is the output?\n\nnums = [-4, -1, 0, 3, 10]\nresult = [x**2 for x in nums]\nresult.sort()\nprint(result)",
      options: JSON.stringify(["[0, 1, 9, 16, 100]", "[16, 1, 0, 9, 100]", "[100, 16, 9, 1, 0]", "[0, 1, 16, 9, 100]"]),
      correctAnswer: "[0, 1, 9, 16, 100]",
      explanation: "Squares: [16, 1, 0, 9, 100]. After sorting: [0, 1, 9, 16, 100]. Two pointers can do this in O(n) without sorting.",
      xpReward: 10,
    },
    {
      type: "pattern-match",
      topic: "two-pointers",
      difficulty: "intermediate",
      question: "Sort Colors (Dutch National Flag): how many pointers are needed?",
      options: JSON.stringify(["Three (lo, mid, hi)", "Two (left, right)", "One", "Four"]),
      correctAnswer: "Three (lo, mid, hi)",
      explanation: "lo tracks where next 0 goes, hi tracks where next 2 goes, mid scans through. Single pass O(n).",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "two-pointers",
      difficulty: "intermediate",
      question: "What is the output?\n\ndef build(s):\n    stack = []\n    for c in s:\n        if c == '#':\n            if stack: stack.pop()\n        else: stack.append(c)\n    return ''.join(stack)\nprint(build('ab#c') == build('ad#c'))",
      options: JSON.stringify(["True", "False", "Error", "'ac'"]),
      correctAnswer: "True",
      explanation: "build('ab#c') → 'ac' (b is deleted). build('ad#c') → 'ac' (d is deleted). Both equal 'ac'.",
      xpReward: 15,
    },
    {
      type: "time-complexity",
      topic: "two-pointers",
      difficulty: "intermediate",
      question: "What is the time complexity of 3Sum?",
      options: JSON.stringify(["O(n²)", "O(n³)", "O(n log n)", "O(n)"]),
      correctAnswer: "O(n²)",
      explanation: "Sort O(n log n) + fix one number and use two pointers O(n) = O(n²) total.",
      xpReward: 15,
    },
    {
      type: "pattern-match",
      topic: "two-pointers",
      difficulty: "beginner",
      question: "Remove Duplicates from Sorted Array: which two-pointer technique?",
      options: JSON.stringify(["Slow/fast pointers (same direction)", "Left/right pointers (opposite direction)", "Sliding window", "Two separate arrays"]),
      correctAnswer: "Slow/fast pointers (same direction)",
      explanation: "Slow marks the position of the last unique element. Fast scans ahead. When fast finds a new value, slow advances and copies.",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "two-pointers",
      difficulty: "intermediate",
      question: "What is the output?\n\nheight = [0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]\nleft, right = 0, len(height)-1\nleft_max = right_max = water = 0\nwhile left < right:\n    if height[left] < height[right]:\n        if height[left] >= left_max: left_max = height[left]\n        else: water += left_max - height[left]\n        left += 1\n    else:\n        if height[right] >= right_max: right_max = height[right]\n        else: water += right_max - height[right]\n        right -= 1\nprint(water)",
      options: JSON.stringify(["6", "8", "5", "7"]),
      correctAnswer: "6",
      explanation: "Trapping Rain Water with two pointers: the classic result for this elevation map is 6 units of water.",
      xpReward: 15,
    },

    // ══════════════════════════════════════════════════════════════
    // MATRIX — 4 cards
    // ══════════════════════════════════════════════════════════════
    {
      type: "predict-output",
      topic: "arrays",
      difficulty: "intermediate",
      question: "What is the output?\n\nmatrix = [[1,2],[3,4]]\nfor i in range(2):\n    for j in range(i+1, 2):\n        matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]\nfor row in matrix: row.reverse()\nprint(matrix)",
      options: JSON.stringify(["[[3, 1], [4, 2]]", "[[4, 3], [2, 1]]", "[[2, 4], [1, 3]]", "[[1, 3], [2, 4]]"]),
      correctAnswer: "[[3, 1], [4, 2]]",
      explanation: "Transpose: [[1,3],[2,4]]. Reverse each row: [[3,1],[4,2]]. This is a 90° clockwise rotation.",
      xpReward: 15,
    },
    {
      type: "pattern-match",
      topic: "arrays",
      difficulty: "intermediate",
      question: "Rotate Image 90° clockwise: what are the two steps?",
      options: JSON.stringify(["Transpose, then reverse each row", "Reverse each row, then transpose", "Reverse each column, then transpose", "Rotate each layer"]),
      correctAnswer: "Transpose, then reverse each row",
      explanation: "Transpose swaps rows and columns. Then reversing each row gives the 90° clockwise rotation.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "arrays",
      difficulty: "intermediate",
      question: "What is the output?\n\nmatrix = [[1,2,3],[4,5,6],[7,8,9]]\nresult = []\nwhile matrix:\n    result += matrix.pop(0)\nprint(result[:4])",
      options: JSON.stringify(["[1, 2, 3, 4]", "[1, 4, 7, 2]", "[1, 2, 3, 6]", "[7, 8, 9, 4]"]),
      correctAnswer: "[1, 2, 3, 4]",
      explanation: "First pop(0) gives [1,2,3]. Second gives [4,5,6]. First 4 elements: [1,2,3,4].",
      xpReward: 15,
    },
    {
      type: "pattern-match",
      topic: "arrays",
      difficulty: "intermediate",
      question: "Set Matrix Zeroes in O(1) space: what do you use as markers?",
      options: JSON.stringify(["First row and first column", "A separate boolean array", "Negative numbers", "The diagonal"]),
      correctAnswer: "First row and first column",
      explanation: "Use the first row and column to mark which rows/columns should be zeroed. Two extra booleans track if the first row/column themselves need zeroing.",
      xpReward: 15,
    },
  ];

  // ── Insert via createMany for speed ──────────────────────────
  let created = 0;
  for (const card of cards) {
    try {
      await prisma.predictionCard.create({ data: card });
      created++;
    } catch (e) {
      // Skip duplicates (if question already exists)
      console.warn(`  ⚠ Skipped card: ${(e as Error).message?.slice(0, 80)}`);
    }
  }

  const total = await prisma.predictionCard.count();
  console.log(`  ✅ Created ${created}/${cards.length} expansion cards`);
  console.log(`     Total prediction cards in DB: ${total}`);
}

if (require.main === module || process.argv[1]?.includes("seed-cards-expansion")) {
  seedExpansionCards()
    .catch((e) => { console.error("❌ Seed failed:", e); process.exit(1); })
    .finally(() => prisma.$disconnect());
}
