import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export async function seedCards() {
  console.log("🃏 Seeding 60+ prediction cards...\n");

  // Delete existing prediction cards and their reviews to avoid conflicts
  await prisma.cardReview.deleteMany({});
  await prisma.predictionCard.deleteMany({});
  console.log("  Cleared existing cards.\n");

  const cards = [
    // ══════════════════════════════════════════
    //  ARRAYS — 12 cards
    // ══════════════════════════════════════════
    {
      type: "predict-output",
      topic: "arrays",
      difficulty: "beginner",
      question: "What is the output?\n\narr = [10, 20, 30, 40, 50]\nprint(arr[2])",
      options: JSON.stringify(["20", "30", "40", "IndexError"]),
      correctAnswer: "30",
      explanation: "Python uses 0-based indexing, so arr[2] accesses the third element which is 30.",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "arrays",
      difficulty: "beginner",
      question: "What is the output?\n\narr = [1, 2, 3, 4, 5]\nprint(arr[-1])",
      options: JSON.stringify(["5", "1", "Error", "4"]),
      correctAnswer: "5",
      explanation: "Negative indexing in Python starts from the end. arr[-1] returns the last element.",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "arrays",
      difficulty: "beginner",
      question: "What is the output?\n\narr = [1, 2, 3]\narr.append(4)\nprint(len(arr))",
      options: JSON.stringify(["3", "4", "5", "Error"]),
      correctAnswer: "4",
      explanation: "append() adds one element to the end. Original length 3 + 1 = 4.",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "arrays",
      difficulty: "intermediate",
      question: "What is the output?\n\narr = [3, 1, 4, 1, 5, 9]\nprint(arr[1:4])",
      options: JSON.stringify(["[1, 4, 1]", "[3, 1, 4]", "[1, 4, 1, 5]", "[3, 1, 4, 1]"]),
      correctAnswer: "[1, 4, 1]",
      explanation: "Slicing arr[1:4] returns elements at indices 1, 2, 3 (end index is exclusive).",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "arrays",
      difficulty: "intermediate",
      question: "What is the output?\n\narr = [1, 2, 3, 4, 5]\narr[1:3] = [20, 30, 40]\nprint(arr)",
      options: JSON.stringify(["[1, 20, 30, 40, 4, 5]", "[1, 20, 30, 4, 5]", "[1, 20, 30, 40, 5]", "Error"]),
      correctAnswer: "[1, 20, 30, 40, 4, 5]",
      explanation: "Slice assignment replaces elements at indices 1-2 with three new elements. Length changes from 5 to 6.",
      xpReward: 15,
    },
    {
      type: "multiple-choice",
      topic: "arrays",
      difficulty: "beginner",
      question: "What is the time complexity of accessing an element by index in a Python list?",
      options: JSON.stringify(["O(1)", "O(n)", "O(log n)", "O(n²)"]),
      correctAnswer: "O(1)",
      explanation: "Python lists are backed by dynamic arrays with direct memory addressing, so index access is O(1).",
      xpReward: 10,
    },
    {
      type: "multiple-choice",
      topic: "arrays",
      difficulty: "intermediate",
      question: "What is the time complexity of inserting at the beginning of a Python list (list.insert(0, x))?",
      options: JSON.stringify(["O(1)", "O(n)", "O(log n)", "O(n²)"]),
      correctAnswer: "O(n)",
      explanation: "Inserting at index 0 requires shifting all existing elements one position to the right, which takes O(n) time.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "arrays",
      difficulty: "intermediate",
      question: "What is the output?\n\na = [1, 2, 3]\nb = a\nb.append(4)\nprint(a)",
      options: JSON.stringify(["[1, 2, 3]", "[1, 2, 3, 4]", "[4, 1, 2, 3]", "Error"]),
      correctAnswer: "[1, 2, 3, 4]",
      explanation: "b = a creates a reference, not a copy. Both a and b point to the same list, so modifying b also modifies a.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "arrays",
      difficulty: "advanced",
      question: "What is the output?\n\narr = [[0]*3 for _ in range(3)]\narr[0][1] = 5\nprint(arr)",
      options: JSON.stringify(["[[0, 5, 0], [0, 0, 0], [0, 0, 0]]", "[[0, 5, 0], [0, 5, 0], [0, 5, 0]]", "Error", "[[5, 5, 5], [0, 0, 0], [0, 0, 0]]"]),
      correctAnswer: "[[0, 5, 0], [0, 0, 0], [0, 0, 0]]",
      explanation: "List comprehension creates independent inner lists. Only arr[0][1] is modified. (Unlike [[0]*3]*3 which shares references!)",
      xpReward: 20,
    },
    {
      type: "predict-output",
      topic: "arrays",
      difficulty: "advanced",
      question: "What is the output?\n\narr = [[0]*3]*3\narr[0][1] = 5\nprint(arr)",
      options: JSON.stringify(["[[0, 5, 0], [0, 0, 0], [0, 0, 0]]", "[[0, 5, 0], [0, 5, 0], [0, 5, 0]]", "[[5, 5, 5], [5, 5, 5], [5, 5, 5]]", "Error"]),
      correctAnswer: "[[0, 5, 0], [0, 5, 0], [0, 5, 0]]",
      explanation: "Using *3 creates 3 references to the SAME inner list. Modifying one row modifies all rows. This is a common Python gotcha!",
      xpReward: 20,
    },
    {
      type: "multiple-choice",
      topic: "arrays",
      difficulty: "advanced",
      question: "Which algorithm does Kadane's algorithm solve?",
      options: JSON.stringify(["Maximum subarray sum", "Finding duplicates", "Sorting in O(n)", "Finding median"]),
      correctAnswer: "Maximum subarray sum",
      explanation: "Kadane's algorithm finds the contiguous subarray with the maximum sum in O(n) time using dynamic programming.",
      xpReward: 20,
    },
    {
      type: "predict-output",
      topic: "arrays",
      difficulty: "intermediate",
      question: "What is the output?\n\nnums = [4, 2, 7, 1, 9]\nprint(max(nums) - min(nums))",
      options: JSON.stringify(["8", "7", "5", "9"]),
      correctAnswer: "8",
      explanation: "max(nums) = 9, min(nums) = 1, so 9 - 1 = 8.",
      xpReward: 10,
    },

    // ══════════════════════════════════════════
    //  STRINGS — 8 cards
    // ══════════════════════════════════════════
    {
      type: "predict-output",
      topic: "strings",
      difficulty: "beginner",
      question: "What is the output?\n\ns = \"hello\"\nprint(s[::-1])",
      options: JSON.stringify(["\"olleh\"", "\"hello\"", "\"h\"", "Error"]),
      correctAnswer: "\"olleh\"",
      explanation: "s[::-1] reverses a string. The step -1 traverses from end to beginning.",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "strings",
      difficulty: "beginner",
      question: "What is the output?\n\ns = \"Python\"\nprint(s[0] + s[-1])",
      options: JSON.stringify(["\"Pn\"", "\"Py\"", "\"on\"", "Error"]),
      correctAnswer: "\"Pn\"",
      explanation: "s[0] is 'P' (first character) and s[-1] is 'n' (last character). Concatenated: 'Pn'.",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "strings",
      difficulty: "intermediate",
      question: "What is the output?\n\ns = \"abcabc\"\nprint(len(set(s)))",
      options: JSON.stringify(["3", "6", "2", "Error"]),
      correctAnswer: "3",
      explanation: "set(s) removes duplicates: {'a', 'b', 'c'}. Length is 3 unique characters.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "strings",
      difficulty: "intermediate",
      question: "What is the output?\n\nwords = \"hello world python\"\nprint(words.split()[1])",
      options: JSON.stringify(["\"hello\"", "\"world\"", "\"python\"", "\"o\""]),
      correctAnswer: "\"world\"",
      explanation: "split() splits on whitespace → ['hello', 'world', 'python']. Index [1] is 'world'.",
      xpReward: 15,
    },
    {
      type: "multiple-choice",
      topic: "strings",
      difficulty: "beginner",
      question: "Are Python strings mutable or immutable?",
      options: JSON.stringify(["Immutable", "Mutable", "Depends on the string", "Only mutable with special methods"]),
      correctAnswer: "Immutable",
      explanation: "Python strings are immutable — you cannot change individual characters. Operations like replace() return a new string.",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "strings",
      difficulty: "intermediate",
      question: "What is the output?\n\ns = \"racecar\"\nprint(s == s[::-1])",
      options: JSON.stringify(["True", "False", "Error", "None"]),
      correctAnswer: "True",
      explanation: "'racecar' reversed is still 'racecar' — it's a palindrome. So the comparison returns True.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "strings",
      difficulty: "advanced",
      question: "What does this function return?\n\ndef f(s):\n    chars = {}\n    start = maxlen = 0\n    for i, c in enumerate(s):\n        if c in chars and chars[c] >= start:\n            start = chars[c] + 1\n        chars[c] = i\n        maxlen = max(maxlen, i - start + 1)\n    return maxlen\n\nprint(f(\"abcabcbb\"))",
      options: JSON.stringify(["3", "7", "8", "1"]),
      correctAnswer: "3",
      explanation: "This is the sliding window algorithm for 'longest substring without repeating characters'. For 'abcabcbb', the longest is 'abc' with length 3.",
      xpReward: 25,
    },
    {
      type: "multiple-choice",
      topic: "strings",
      difficulty: "intermediate",
      question: "What is the time complexity of checking if a string is a palindrome using two pointers?",
      options: JSON.stringify(["O(n)", "O(n²)", "O(log n)", "O(1)"]),
      correctAnswer: "O(n)",
      explanation: "Two pointers from both ends meet in the middle — each character is checked at most once, giving O(n) time.",
      xpReward: 15,
    },

    // ══════════════════════════════════════════
    //  HASH MAPS / DICTIONARIES — 8 cards
    // ══════════════════════════════════════════
    {
      type: "predict-output",
      topic: "hash-maps",
      difficulty: "beginner",
      question: "What is the output?\n\nd = {\"a\": 1, \"b\": 2, \"c\": 3}\nprint(d[\"b\"])",
      options: JSON.stringify(["1", "2", "3", "KeyError"]),
      correctAnswer: "2",
      explanation: "Dictionary lookup by key: d['b'] returns the value 2.",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "hash-maps",
      difficulty: "beginner",
      question: "What is the output?\n\nd = {}\nd[\"x\"] = 10\nd[\"y\"] = 20\nd[\"x\"] = 30\nprint(d)",
      options: JSON.stringify(["{'x': 30, 'y': 20}", "{'x': 10, 'y': 20}", "{'x': 10, 'x': 30, 'y': 20}", "Error"]),
      correctAnswer: "{'x': 30, 'y': 20}",
      explanation: "Dictionary keys are unique. Setting d['x'] = 30 overwrites the previous value of 10.",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "hash-maps",
      difficulty: "intermediate",
      question: "What is the output?\n\nfrom collections import Counter\nprint(Counter(\"abracadabra\"))",
      options: JSON.stringify(["Counter({'a': 5, 'b': 2, 'r': 2, 'c': 1, 'd': 1})", "Counter({'a': 4, 'b': 2, 'r': 2, 'c': 1, 'd': 1})", "{'a': 5, 'b': 2}", "Error"]),
      correctAnswer: "Counter({'a': 5, 'b': 2, 'r': 2, 'c': 1, 'd': 1})",
      explanation: "Counter counts character frequencies: a=5, b=2, r=2, c=1, d=1.",
      xpReward: 15,
    },
    {
      type: "multiple-choice",
      topic: "hash-maps",
      difficulty: "beginner",
      question: "What is the average time complexity of dictionary lookup in Python?",
      options: JSON.stringify(["O(1)", "O(n)", "O(log n)", "O(n²)"]),
      correctAnswer: "O(1)",
      explanation: "Python dictionaries use hash tables which provide O(1) average-case lookup, insertion, and deletion.",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "hash-maps",
      difficulty: "intermediate",
      question: "What is the output?\n\nd = {\"a\": 1, \"b\": 2}\nprint(d.get(\"c\", 0))",
      options: JSON.stringify(["0", "None", "KeyError", "1"]),
      correctAnswer: "0",
      explanation: "dict.get(key, default) returns the default value if the key is not found. 'c' is not in d, so it returns 0.",
      xpReward: 15,
    },
    {
      type: "multiple-choice",
      topic: "hash-maps",
      difficulty: "intermediate",
      question: "Which approach does Two Sum typically use for an O(n) solution?",
      options: JSON.stringify(["Hash map to store complement", "Sorting + binary search", "Brute force two loops", "Sliding window"]),
      correctAnswer: "Hash map to store complement",
      explanation: "For each number, store it in a hash map. Check if (target - number) already exists. One pass, O(n) time, O(n) space.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "hash-maps",
      difficulty: "advanced",
      question: "What does this return?\n\ndef group_anagrams(strs):\n    groups = {}\n    for s in strs:\n        key = tuple(sorted(s))\n        groups.setdefault(key, []).append(s)\n    return list(groups.values())\n\nprint(len(group_anagrams([\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"])))",
      options: JSON.stringify(["3", "6", "2", "4"]),
      correctAnswer: "3",
      explanation: "3 anagram groups: ['eat','tea','ate'], ['tan','nat'], ['bat']. Using sorted tuple as key groups anagrams together.",
      xpReward: 20,
    },
    {
      type: "predict-output",
      topic: "hash-maps",
      difficulty: "intermediate",
      question: "What is the output?\n\nfrom collections import defaultdict\nd = defaultdict(list)\nd[\"a\"].append(1)\nd[\"a\"].append(2)\nd[\"b\"].append(3)\nprint(dict(d))",
      options: JSON.stringify(["{'a': [1, 2], 'b': [3]}", "{'a': 2, 'b': 3}", "Error", "{'a': [1], 'b': [3]}"]),
      correctAnswer: "{'a': [1, 2], 'b': [3]}",
      explanation: "defaultdict(list) auto-creates empty lists for new keys. Two appends to 'a' give [1, 2].",
      xpReward: 15,
    },

    // ══════════════════════════════════════════
    //  STACKS & QUEUES — 8 cards
    // ══════════════════════════════════════════
    {
      type: "predict-output",
      topic: "stacks",
      difficulty: "beginner",
      question: "What is the output?\n\nstack = []\nstack.append(1)\nstack.append(2)\nstack.append(3)\nprint(stack.pop())",
      options: JSON.stringify(["3", "1", "2", "Error"]),
      correctAnswer: "3",
      explanation: "Stacks are LIFO (Last In, First Out). The last item pushed (3) is the first popped.",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "stacks",
      difficulty: "beginner",
      question: "What is the output?\n\nstack = [10, 20, 30]\nstack.pop()\nstack.pop()\nprint(stack)",
      options: JSON.stringify(["[10]", "[30]", "[10, 20]", "[]"]),
      correctAnswer: "[10]",
      explanation: "Two pops remove 30 then 20 (LIFO order). Only 10 remains.",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "stacks",
      difficulty: "intermediate",
      question: "What does this function return for input \"({[]})\"?\n\ndef is_valid(s):\n    stack = []\n    pairs = {')':'(', '}':'{', ']':'['}\n    for c in s:\n        if c in '({[':\n            stack.append(c)\n        elif stack and stack[-1] == pairs[c]:\n            stack.pop()\n        else:\n            return False\n    return len(stack) == 0\n\nprint(is_valid(\"({[]})\"))",
      options: JSON.stringify(["True", "False", "Error", "None"]),
      correctAnswer: "True",
      explanation: "Stack processes each bracket: push (, {, [, then ] matches [, } matches {, ) matches (. Stack is empty → valid.",
      xpReward: 20,
    },
    {
      type: "multiple-choice",
      topic: "stacks",
      difficulty: "beginner",
      question: "Which data structure principle does a stack follow?",
      options: JSON.stringify(["LIFO (Last In, First Out)", "FIFO (First In, First Out)", "Random access", "Priority ordering"]),
      correctAnswer: "LIFO (Last In, First Out)",
      explanation: "A stack follows LIFO — the last element pushed is the first one popped. Think of a stack of plates.",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "stacks",
      difficulty: "intermediate",
      question: "What is the output?\n\nfrom collections import deque\nq = deque()\nq.append(1)\nq.append(2)\nq.append(3)\nprint(q.popleft())",
      options: JSON.stringify(["1", "3", "2", "Error"]),
      correctAnswer: "1",
      explanation: "deque with popleft() acts as a FIFO queue. The first element added (1) is the first removed.",
      xpReward: 15,
    },
    {
      type: "multiple-choice",
      topic: "stacks",
      difficulty: "intermediate",
      question: "What is the time complexity of push and pop operations on a stack (using a Python list)?",
      options: JSON.stringify(["O(1) amortized", "O(n)", "O(log n)", "O(n²)"]),
      correctAnswer: "O(1) amortized",
      explanation: "list.append() and list.pop() both operate at the end of the list, which is O(1) amortized time.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "stacks",
      difficulty: "advanced",
      question: "What does this code produce?\n\ndef next_greater(nums):\n    result = [-1] * len(nums)\n    stack = []\n    for i, num in enumerate(nums):\n        while stack and nums[stack[-1]] < num:\n            result[stack.pop()] = num\n        stack.append(i)\n    return result\n\nprint(next_greater([2, 1, 2, 4, 3]))",
      options: JSON.stringify(["[4, 2, 4, -1, -1]", "[1, 2, 4, 3, -1]", "[4, 4, 4, -1, -1]", "[-1, 2, 4, -1, -1]"]),
      correctAnswer: "[4, 2, 4, -1, -1]",
      explanation: "Monotonic stack pattern: for each element, the next greater element is found. 2→4, 1→2, 2→4, 4→none(-1), 3→none(-1).",
      xpReward: 25,
    },
    {
      type: "multiple-choice",
      topic: "stacks",
      difficulty: "intermediate",
      question: "Which problem is typically solved using a monotonic stack?",
      options: JSON.stringify(["Next greater element", "Two sum", "Binary search", "Merge sort"]),
      correctAnswer: "Next greater element",
      explanation: "A monotonic stack maintains elements in increasing/decreasing order and efficiently finds the next greater/smaller element for each position.",
      xpReward: 15,
    },

    // ══════════════════════════════════════════
    //  LINKED LISTS — 6 cards
    // ══════════════════════════════════════════
    {
      type: "multiple-choice",
      topic: "linked-lists",
      difficulty: "beginner",
      question: "What is the time complexity of accessing the nth element in a singly linked list?",
      options: JSON.stringify(["O(n)", "O(1)", "O(log n)", "O(n²)"]),
      correctAnswer: "O(n)",
      explanation: "Unlike arrays, linked lists don't support random access. You must traverse from the head, visiting one node at a time.",
      xpReward: 10,
    },
    {
      type: "multiple-choice",
      topic: "linked-lists",
      difficulty: "beginner",
      question: "What advantage does a linked list have over an array for insertions?",
      options: JSON.stringify(["O(1) insertion at beginning", "O(1) random access", "Less memory usage", "Faster sorting"]),
      correctAnswer: "O(1) insertion at beginning",
      explanation: "Inserting at the beginning of a linked list is O(1) — just create a new node and point it to the head. Arrays require O(n) shifting.",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "linked-lists",
      difficulty: "intermediate",
      question: "What is the output of this linked list reversal?\n\ndef reverse(lst):\n    prev = None\n    for val in lst:\n        prev = [val, prev]\n    result = []\n    while prev:\n        result.append(prev[0])\n        prev = prev[1]\n    return result\n\nprint(reverse([1, 2, 3, 4]))",
      options: JSON.stringify(["[4, 3, 2, 1]", "[1, 2, 3, 4]", "[1]", "Error"]),
      correctAnswer: "[4, 3, 2, 1]",
      explanation: "The function builds a reversed linked list by prepending each element. Traversing it gives [4, 3, 2, 1].",
      xpReward: 15,
    },
    {
      type: "multiple-choice",
      topic: "linked-lists",
      difficulty: "intermediate",
      question: "Which algorithm detects a cycle in a linked list in O(1) space?",
      options: JSON.stringify(["Floyd's Tortoise and Hare", "Dijkstra's algorithm", "BFS on the list", "Hash set approach"]),
      correctAnswer: "Floyd's Tortoise and Hare",
      explanation: "Floyd's algorithm uses two pointers (slow=1 step, fast=2 steps). If they meet, there's a cycle. O(n) time, O(1) space.",
      xpReward: 15,
    },
    {
      type: "multiple-choice",
      topic: "linked-lists",
      difficulty: "advanced",
      question: "What is the time complexity of merging two sorted linked lists?",
      options: JSON.stringify(["O(n + m)", "O(n × m)", "O(n log n)", "O(max(n, m))"]),
      correctAnswer: "O(n + m)",
      explanation: "Each element from both lists is visited exactly once. We compare heads and advance the smaller one. Total: O(n + m).",
      xpReward: 20,
    },
    {
      type: "multiple-choice",
      topic: "linked-lists",
      difficulty: "intermediate",
      question: "How do you find the middle node of a linked list in one pass?",
      options: JSON.stringify(["Slow pointer (1x) and fast pointer (2x)", "Count nodes then traverse to n/2", "Use a stack", "Binary search on the list"]),
      correctAnswer: "Slow pointer (1x) and fast pointer (2x)",
      explanation: "When the fast pointer reaches the end, the slow pointer is at the middle. One pass, O(n) time, O(1) space.",
      xpReward: 15,
    },

    // ══════════════════════════════════════════
    //  TREES — 8 cards
    // ══════════════════════════════════════════
    {
      type: "predict-output",
      topic: "trees",
      difficulty: "beginner",
      treeValues: JSON.stringify([5, 3, 7, 1, 4]),
      question: "Given BST built by inserting [5, 3, 7, 1, 4]:\nWhat is the in-order traversal?",
      options: JSON.stringify(["[1, 3, 4, 5, 7]", "[5, 3, 1, 4, 7]", "[5, 3, 7, 1, 4]", "[1, 4, 3, 7, 5]"]),
      correctAnswer: "[1, 3, 4, 5, 7]",
      explanation: "In-order traversal of a BST visits nodes in sorted order: left → root → right. Result: 1, 3, 4, 5, 7.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "trees",
      difficulty: "beginner",
      treeValues: JSON.stringify([10, 5, 15, 3, 7]),
      question: "BST from insertions [10, 5, 15, 3, 7]:\nWhat is the pre-order traversal?",
      options: JSON.stringify(["[10, 5, 3, 7, 15]", "[3, 5, 7, 10, 15]", "[10, 5, 15, 3, 7]", "[3, 7, 5, 15, 10]"]),
      correctAnswer: "[10, 5, 3, 7, 15]",
      explanation: "Pre-order: root → left → right. Visit 10, then left subtree (5, 3, 7), then right (15).",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "trees",
      difficulty: "intermediate",
      treeValues: JSON.stringify([8, 4, 12, 2, 6, 10, 14]),
      question: "BST from [8, 4, 12, 2, 6, 10, 14]:\nWhat is the height of this tree?",
      options: JSON.stringify(["3", "4", "2", "7"]),
      correctAnswer: "3",
      explanation: "This is a perfectly balanced BST. Root (8) at level 1, children at level 2, grandchildren at level 3. Height = 3.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "trees",
      difficulty: "intermediate",
      treeValues: JSON.stringify([5, 3, 7, 2, 4, 6, 8]),
      question: "BST from [5, 3, 7, 2, 4, 6, 8]:\nWhat is the level-order (BFS) traversal?",
      options: JSON.stringify(["[5, 3, 7, 2, 4, 6, 8]", "[2, 3, 4, 5, 6, 7, 8]", "[5, 3, 2, 4, 7, 6, 8]", "[8, 6, 7, 4, 2, 3, 5]"]),
      correctAnswer: "[5, 3, 7, 2, 4, 6, 8]",
      explanation: "Level-order visits nodes level by level, left to right: Root 5 → Level 2: 3, 7 → Level 3: 2, 4, 6, 8.",
      xpReward: 15,
    },
    {
      type: "multiple-choice",
      topic: "trees",
      difficulty: "beginner",
      question: "In a Binary Search Tree (BST), where are values smaller than the root stored?",
      options: JSON.stringify(["Left subtree", "Right subtree", "Either subtree", "At the root"]),
      correctAnswer: "Left subtree",
      explanation: "BST property: all values in the left subtree are less than the root, and all values in the right subtree are greater.",
      xpReward: 10,
    },
    {
      type: "multiple-choice",
      topic: "trees",
      difficulty: "intermediate",
      question: "What is the time complexity of searching in a balanced BST?",
      options: JSON.stringify(["O(log n)", "O(n)", "O(1)", "O(n log n)"]),
      correctAnswer: "O(log n)",
      explanation: "In a balanced BST, each comparison eliminates half the remaining nodes, giving O(log n) time — similar to binary search.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "trees",
      difficulty: "advanced",
      treeValues: JSON.stringify([1, 2, 3, 4, 5]),
      question: "BST from sequential insertions [1, 2, 3, 4, 5]:\nWhat is the height of this tree?",
      options: JSON.stringify(["5", "3", "2", "4"]),
      correctAnswer: "5",
      explanation: "Inserting sorted values into a BST creates a degenerate (skewed) tree — essentially a linked list. Height equals the number of nodes: 5.",
      xpReward: 20,
    },
    {
      type: "multiple-choice",
      topic: "trees",
      difficulty: "advanced",
      question: "Which traversal can uniquely reconstruct a BST from a single traversal?",
      options: JSON.stringify(["Pre-order", "In-order", "Post-order", "Level-order"]),
      correctAnswer: "Pre-order",
      explanation: "Pre-order uniquely defines a BST because the BST property lets us determine left/right split. In-order alone produces a sorted list, which could map to many BSTs.",
      xpReward: 20,
    },

    // ══════════════════════════════════════════
    //  SORTING & SEARCHING — 6 cards
    // ══════════════════════════════════════════
    {
      type: "predict-output",
      topic: "sorting",
      difficulty: "beginner",
      question: "What is the output?\n\narr = [3, 1, 4, 1, 5, 9]\narr.sort()\nprint(arr)",
      options: JSON.stringify(["[1, 1, 3, 4, 5, 9]", "[9, 5, 4, 3, 1, 1]", "[3, 1, 4, 1, 5, 9]", "Error"]),
      correctAnswer: "[1, 1, 3, 4, 5, 9]",
      explanation: "list.sort() sorts in-place in ascending order. Python uses Timsort, which is stable and O(n log n).",
      xpReward: 10,
    },
    {
      type: "multiple-choice",
      topic: "sorting",
      difficulty: "intermediate",
      question: "What is the time complexity of Python's built-in sort (Timsort)?",
      options: JSON.stringify(["O(n log n)", "O(n²)", "O(n)", "O(log n)"]),
      correctAnswer: "O(n log n)",
      explanation: "Timsort is a hybrid sorting algorithm (merge sort + insertion sort) with O(n log n) worst case and O(n) best case.",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "sorting",
      difficulty: "intermediate",
      question: "What is the output?\n\ndef binary_search(arr, target):\n    lo, hi = 0, len(arr) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return -1\n\nprint(binary_search([1,3,5,7,9,11], 7))",
      options: JSON.stringify(["3", "4", "7", "-1"]),
      correctAnswer: "3",
      explanation: "Binary search finds 7 at index 3: mid=2 (5<7, go right), mid=4 (9>7, go left), mid=3 (7==7, found!).",
      xpReward: 15,
    },
    {
      type: "multiple-choice",
      topic: "sorting",
      difficulty: "beginner",
      question: "Which sorting algorithm has the best average-case time complexity?",
      options: JSON.stringify(["Merge Sort — O(n log n)", "Bubble Sort — O(n²)", "Selection Sort — O(n²)", "Insertion Sort — O(n²)"]),
      correctAnswer: "Merge Sort — O(n log n)",
      explanation: "Merge Sort achieves O(n log n) in all cases (best, average, worst), making it more efficient than quadratic algorithms.",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "sorting",
      difficulty: "advanced",
      question: "What is the output? (Counting sort concept)\n\ndef count_sort_range(arr):\n    counts = [0] * (max(arr) + 1)\n    for x in arr:\n        counts[x] += 1\n    return [i for i, c in enumerate(counts) for _ in range(c)]\n\nprint(count_sort_range([4, 2, 2, 6, 1]))",
      options: JSON.stringify(["[1, 2, 2, 4, 6]", "[4, 2, 2, 6, 1]", "[1, 2, 4, 6]", "[6, 4, 2, 2, 1]"]),
      correctAnswer: "[1, 2, 2, 4, 6]",
      explanation: "Counting sort: count occurrences then reconstruct. O(n + k) time where k is max value. Preserves duplicates.",
      xpReward: 20,
    },
    {
      type: "multiple-choice",
      topic: "sorting",
      difficulty: "advanced",
      question: "What is the space complexity of Merge Sort?",
      options: JSON.stringify(["O(n)", "O(1)", "O(log n)", "O(n²)"]),
      correctAnswer: "O(n)",
      explanation: "Merge Sort requires O(n) auxiliary space for the temporary merged arrays during the merge step.",
      xpReward: 20,
    },

    // ══════════════════════════════════════════
    //  DYNAMIC PROGRAMMING — 6 cards
    // ══════════════════════════════════════════
    {
      type: "predict-output",
      topic: "dynamic-programming",
      difficulty: "beginner",
      question: "What is the output? (Fibonacci with DP)\n\ndef fib(n):\n    dp = [0, 1]\n    for i in range(2, n + 1):\n        dp.append(dp[i-1] + dp[i-2])\n    return dp[n]\n\nprint(fib(6))",
      options: JSON.stringify(["8", "13", "5", "6"]),
      correctAnswer: "8",
      explanation: "Fibonacci sequence: 0, 1, 1, 2, 3, 5, 8. fib(6) = 8.",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "dynamic-programming",
      difficulty: "intermediate",
      question: "What does this function return?\n\ndef climb(n):\n    if n <= 2:\n        return n\n    a, b = 1, 2\n    for _ in range(3, n + 1):\n        a, b = b, a + b\n    return b\n\nprint(climb(5))",
      options: JSON.stringify(["8", "5", "13", "3"]),
      correctAnswer: "8",
      explanation: "Climbing stairs (1 or 2 steps): ways(1)=1, ways(2)=2, ways(3)=3, ways(4)=5, ways(5)=8. Same as Fibonacci shifted by 1.",
      xpReward: 15,
    },
    {
      type: "multiple-choice",
      topic: "dynamic-programming",
      difficulty: "beginner",
      question: "What are the two key properties of a dynamic programming problem?",
      options: JSON.stringify(["Overlapping subproblems + Optimal substructure", "Divide and conquer + Greedy choice", "Recursion + Sorting", "Two pointers + Sliding window"]),
      correctAnswer: "Overlapping subproblems + Optimal substructure",
      explanation: "DP works when the problem has overlapping subproblems (same subproblems solved multiple times) and optimal substructure (optimal solution built from optimal solutions to subproblems).",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "dynamic-programming",
      difficulty: "intermediate",
      question: "What does coin_change([1, 5, 10], 12) return?\n\ndef coin_change(coins, amount):\n    dp = [float('inf')] * (amount + 1)\n    dp[0] = 0\n    for i in range(1, amount + 1):\n        for c in coins:\n            if c <= i:\n                dp[i] = min(dp[i], dp[i-c] + 1)\n    return dp[amount] if dp[amount] != float('inf') else -1",
      options: JSON.stringify(["3", "2", "12", "4"]),
      correctAnswer: "3",
      explanation: "Minimum coins for 12: use 10 + 1 + 1 = 3 coins. The DP table builds up from 0 to 12, trying each coin denomination.",
      xpReward: 20,
    },
    {
      type: "predict-output",
      topic: "dynamic-programming",
      difficulty: "advanced",
      question: "What does this function return?\n\ndef rob(nums):\n    if not nums:\n        return 0\n    prev2, prev1 = 0, 0\n    for n in nums:\n        prev2, prev1 = prev1, max(prev1, prev2 + n)\n    return prev1\n\nprint(rob([2, 7, 9, 3, 1]))",
      options: JSON.stringify(["12", "11", "10", "13"]),
      correctAnswer: "12",
      explanation: "House Robber: Can't rob adjacent houses. Best: rob houses with [2, 9, 1] = 12, or [7, 3] = 10. Maximum is 12.",
      xpReward: 20,
    },
    {
      type: "multiple-choice",
      topic: "dynamic-programming",
      difficulty: "intermediate",
      question: "What is the difference between top-down and bottom-up DP?",
      options: JSON.stringify(["Top-down uses recursion + memoization; Bottom-up uses iteration + tabulation", "They are the same approach with different names", "Top-down is faster; Bottom-up uses less memory", "Top-down works on trees; Bottom-up works on arrays"]),
      correctAnswer: "Top-down uses recursion + memoization; Bottom-up uses iteration + tabulation",
      explanation: "Top-down starts from the main problem and caches results (memoization). Bottom-up builds solutions from smallest subproblems up (tabulation).",
      xpReward: 15,
    },

    // ══════════════════════════════════════════
    //  GRAPHS — 4 cards
    // ══════════════════════════════════════════
    {
      type: "multiple-choice",
      topic: "graphs",
      difficulty: "beginner",
      question: "What is the difference between BFS and DFS?",
      options: JSON.stringify(["BFS explores level by level (queue); DFS explores as deep as possible (stack)", "BFS uses a stack; DFS uses a queue", "BFS is always faster than DFS", "They produce the same result"]),
      correctAnswer: "BFS explores level by level (queue); DFS explores as deep as possible (stack)",
      explanation: "BFS uses a queue for level-by-level exploration. DFS uses a stack (or recursion) to go as deep as possible before backtracking.",
      xpReward: 10,
    },
    {
      type: "multiple-choice",
      topic: "graphs",
      difficulty: "intermediate",
      question: "What is the time complexity of BFS/DFS on a graph with V vertices and E edges?",
      options: JSON.stringify(["O(V + E)", "O(V × E)", "O(V²)", "O(V log V)"]),
      correctAnswer: "O(V + E)",
      explanation: "Both BFS and DFS visit each vertex once (V) and explore each edge once (E), giving O(V + E).",
      xpReward: 15,
    },
    {
      type: "predict-output",
      topic: "graphs",
      difficulty: "intermediate",
      question: "What is the output? (BFS traversal)\n\ndef bfs(graph, start):\n    visited = set()\n    queue = [start]\n    order = []\n    while queue:\n        node = queue.pop(0)\n        if node not in visited:\n            visited.add(node)\n            order.append(node)\n            queue.extend(graph.get(node, []))\n    return order\n\ngraph = {0: [1, 2], 1: [3], 2: [3], 3: []}\nprint(bfs(graph, 0))",
      options: JSON.stringify(["[0, 1, 2, 3]", "[0, 1, 3, 2]", "[0, 2, 1, 3]", "[3, 1, 2, 0]"]),
      correctAnswer: "[0, 1, 2, 3]",
      explanation: "BFS from 0: visit 0, enqueue 1,2 → visit 1, enqueue 3 → visit 2, 3 already queued → visit 3. Result: [0, 1, 2, 3].",
      xpReward: 20,
    },
    {
      type: "multiple-choice",
      topic: "graphs",
      difficulty: "advanced",
      question: "Which algorithm detects if a directed graph has a cycle?",
      options: JSON.stringify(["Topological sort (Kahn's algorithm)", "Dijkstra's algorithm", "Prim's algorithm", "Binary search"]),
      correctAnswer: "Topological sort (Kahn's algorithm)",
      explanation: "If topological sort can't process all vertices, the graph has a cycle. Kahn's algorithm uses in-degree tracking. O(V+E).",
      xpReward: 20,
    },

    // ══════════════════════════════════════════
    //  TWO POINTERS & SLIDING WINDOW — 4 cards
    // ══════════════════════════════════════════
    {
      type: "predict-output",
      topic: "two-pointers",
      difficulty: "intermediate",
      question: "What does this function return?\n\ndef two_sum_sorted(arr, target):\n    l, r = 0, len(arr) - 1\n    while l < r:\n        s = arr[l] + arr[r]\n        if s == target:\n            return [l, r]\n        elif s < target:\n            l += 1\n        else:\n            r -= 1\n    return []\n\nprint(two_sum_sorted([1, 3, 5, 7, 9], 12))",
      options: JSON.stringify(["[1, 4]", "[2, 3]", "[0, 4]", "[3, 4]"]),
      correctAnswer: "[1, 4]",
      explanation: "Two pointers on sorted array: l=0,r=4 (1+9=10<12, l++), l=1,r=4 (3+9=12 == target). Return [1, 4].",
      xpReward: 15,
    },
    {
      type: "multiple-choice",
      topic: "two-pointers",
      difficulty: "beginner",
      question: "When is the two-pointer technique most useful?",
      options: JSON.stringify(["On sorted arrays or when looking for pairs", "Only on linked lists", "When the array is unsorted", "For finding the maximum element"]),
      correctAnswer: "On sorted arrays or when looking for pairs",
      explanation: "Two pointers work best on sorted data where you can eliminate search space by moving one pointer based on comparison results.",
      xpReward: 10,
    },
    {
      type: "predict-output",
      topic: "sliding-window",
      difficulty: "intermediate",
      question: "What does this function return?\n\ndef max_sum_window(arr, k):\n    window = sum(arr[:k])\n    best = window\n    for i in range(k, len(arr)):\n        window += arr[i] - arr[i-k]\n        best = max(best, window)\n    return best\n\nprint(max_sum_window([2, 1, 5, 1, 3, 2], 3))",
      options: JSON.stringify(["9", "8", "7", "10"]),
      correctAnswer: "9",
      explanation: "Fixed-size sliding window of k=3: [2,1,5]=8, [1,5,1]=7, [5,1,3]=9, [1,3,2]=6. Maximum is 9.",
      xpReward: 15,
    },
    {
      type: "multiple-choice",
      topic: "sliding-window",
      difficulty: "intermediate",
      question: "What distinguishes a sliding window from a brute force approach?",
      options: JSON.stringify(["Reuses computation from previous window position", "Uses more memory", "Requires sorting first", "Always uses two pointers"]),
      correctAnswer: "Reuses computation from previous window position",
      explanation: "Sliding window avoids recalculating the entire window. It adds the new element and removes the old one, reducing O(n·k) to O(n).",
      xpReward: 15,
    },
  ];

  let created = 0;
  for (const card of cards) {
    try {
      await prisma.predictionCard.create({
        data: {
          type: card.type,
          topic: card.topic || null,
          difficulty: card.difficulty,
          treeValues: card.treeValues || null,
          question: card.question,
          options: card.options || null,
          correctAnswer: card.correctAnswer,
          explanation: card.explanation,
          xpReward: card.xpReward,
        },
      });
      created++;
    } catch (e) {
      console.log(`  ⚠ Skipped card: ${(e as Error).message?.slice(0, 80)}`);
    }
  }

  console.log(`✅ Seeded ${created}/${cards.length} prediction cards`);
  console.log(`   Total cards in DB: ${await prisma.predictionCard.count()}`);
}

if (require.main === module || process.argv[1]?.includes("seed-cards-60")) {
  seedCards()
    .catch((e) => { console.error("❌ Card seed failed:", e); process.exit(1); })
    .finally(() => prisma.$disconnect());
}
